/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/acc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all accounts
         * @description GET /api/acc
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an account by ID
         * @description GET /api/acc/:account_id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Account"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all networks
         * @description GET /api/net
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworksResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a network
         * @description POST /api/net
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Network"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get network presets
         * @description GET /api/net/presets
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network by ID
         * @description GET /api/net/:network_id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        /**
         * Update a network by ID
         * @description PUT /api/net/:network_id
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a network by ID
         * @description DELETE /api/net/:network_id
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_id}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get network endpoints
         * @description GET /api/net/:network_id/endpoints
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a network endpoint
         * @description POST /api/net/:network_id/endpoints
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_id}/endpoints/{endpoint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network endpoint by ID
         * @description GET /api/net/:network_id/endpoints/:endpoint_id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                    endpoint_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        /**
         * Update a network endpoint by ID
         * @description PUT /api/net/:network_id/endpoints/:endpoint_id
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                    endpoint_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkEndpointUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a network endpoint by ID
         * @description DELETE /api/net/:network_id/endpoints/:endpoint_id
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                    endpoint_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_id}/endpoints/{endpoint_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network endpoint status
         * @description GET /api/net/:network_id/endpoints/:endpoint_id/status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_id: number;
                    endpoint_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RpcStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all vendor flags
         * @description GET /api/health
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** Account */
        Account: {
            /** Format: uuid */
            account_id: string;
            name: string;
            chains: string[];
            metadata: components["schemas"]["WalletType"];
        };
        /** AccountsResponse */
        AccountsResponse: {
            accounts: components["schemas"]["Account"][];
        };
        /** EOAWallet */
        EOAWallet: {
            evm_address: string;
        };
        /** Network */
        Network: {
            /**
             * Format: int32
             * @description evm chain id
             */
            network_identity: number;
            /** @description name, Ethereum Mainnet, Optimism, etc */
            network_name: string;
            /** @description icon url, https://example.com/icon.png, etc */
            network_icon_url?: string;
        };
        /** NetworkEndpoint */
        NetworkEndpoint: {
            endpoint_identity: string;
            endpoint_label?: string;
            endpoint_type: string;
            endpoint_url: string;
            endpoint_disabled: boolean;
            /** Format: int32 */
            network_identity: number;
        };
        /** NetworkEndpointUpdate */
        NetworkEndpointUpdate: {
            endpoint_label?: string;
            endpoint_type?: string;
            endpoint_url?: string;
            endpoint_disabled?: boolean;
        };
        /** NetworkUpdate */
        NetworkUpdate: {
            network_name?: string;
            network_icon_url?: string;
        };
        /** NetworksResponse */
        NetworksResponse: {
            networks: components["schemas"]["Network"][];
        };
        /** RailgunWallet */
        RailgunWallet: {
            railgun_address: string;
        };
        RpcStatus: components["schemas"]["RpcStatus_Alive"] | components["schemas"]["RpcStatus_Dead"] | components["schemas"]["RpcStatus_Disabled"];
        /** RpcStatusAlive */
        RpcStatusAlive: {
            /** Format: uint64 */
            block_number: number;
            /** Format: uint64 */
            chain_id: number;
            /** Format: uint64 */
            timestamp: number;
        };
        /** RpcStatusDead */
        RpcStatusDead: {
            error: string;
        };
        /** RpcStatusDisabled */
        RpcStatusDisabled: Record<string, never>;
        RpcStatus_Alive: {
            /**
             * @example Alive
             * @enum {string}
             */
            status: "Alive";
        } & components["schemas"]["RpcStatusAlive"];
        RpcStatus_Dead: {
            /**
             * @example Dead
             * @enum {string}
             */
            status: "Dead";
        } & components["schemas"]["RpcStatusDead"];
        RpcStatus_Disabled: {
            /**
             * @example Disabled
             * @enum {string}
             */
            status: "Disabled";
        } & components["schemas"]["RpcStatusDisabled"];
        /** SafeWallet */
        SafeWallet: {
            evm_address: string;
        };
        /** ViewWallet */
        ViewWallet: {
            evm_address: string;
        };
        WalletType: components["schemas"]["WalletType_Safe"] | components["schemas"]["WalletType_EOA"] | components["schemas"]["WalletType_View"] | components["schemas"]["WalletType_Railgun"];
        WalletType_EOA: {
            /**
             * @example EOA
             * @enum {string}
             */
            type: "EOA";
        } & components["schemas"]["EOAWallet"];
        WalletType_Railgun: {
            /**
             * @example Railgun
             * @enum {string}
             */
            type: "Railgun";
        } & components["schemas"]["RailgunWallet"];
        WalletType_Safe: {
            /**
             * @example Safe
             * @enum {string}
             */
            type: "Safe";
        } & components["schemas"]["SafeWallet"];
        WalletType_View: {
            /**
             * @example View
             * @enum {string}
             */
            type: "View";
        } & components["schemas"]["ViewWallet"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
