/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/acc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all accounts
         * @description GET /api/acc
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an account
         * @description POST /api/acc
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Account"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Account"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an account by ID
         * @description GET /api/acc/:account_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Account"];
                    };
                };
            };
        };
        /**
         * Update an account by ID
         * @description PUT /api/acc/:account_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AccountUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Account"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete an account by ID
         * @description DELETE /api/acc/:account_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/next-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next account ID
         * @description GET /api/acc/next-id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the assets of an account
         * @description GET /api/acc/:account_identity/assets
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/asset/{asset_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add an asset to an account
         * @description POST /api/acc/:account_identity/asset/:asset_identity
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        /**
         * Remove an asset from an account
         * @description DELETE /api/acc/:account_identity/asset/:asset_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the balances of an account
         * @description GET /api/acc/:account_identity/balances
         */
        get: {
            parameters: {
                query: {
                    display_currency: string;
                };
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountBalances"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all networks
         * @description GET /api/net
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworksResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a network
         * @description POST /api/net
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Network"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get network presets
         * @description GET /api/net/presets
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network by ID
         * @description GET /api/net/:network_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        /**
         * Update a network by ID
         * @description PUT /api/net/:network_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a network by ID
         * @description DELETE /api/net/:network_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover metadata for a network
         * @description GET /api/net/:network_identity/metadata
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkMetadataDiscovery"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get network endpoints
         * @description GET /api/net/:network_identity/endpoints
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a network endpoint
         * @description POST /api/net/:network_identity/endpoints
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/endpoints/next-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next network endpoint ID
         * @description GET /api/net/:network_identity/endpoints/next-id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/endpoints/{endpoint_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network endpoint by ID
         * @description GET /api/net/:network_identity/endpoints/:endpoint_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                    endpoint_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        /**
         * Update a network endpoint by ID
         * @description PUT /api/net/:network_identity/endpoints/:endpoint_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                    endpoint_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkEndpointUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a network endpoint by ID
         * @description DELETE /api/net/:network_identity/endpoints/:endpoint_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                    endpoint_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/endpoints/{endpoint_identity}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network endpoint status
         * @description GET /api/net/:network_identity/endpoints/:endpoint_identity/status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                    endpoint_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RpcStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all assets
         * @description GET /api/asset
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AssetsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an asset
         * @description POST /api/asset
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Asset"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Asset"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/{asset_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an asset by ID
         * @description GET /api/asset/:asset_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Asset"];
                    };
                };
            };
        };
        /**
         * Update an asset by ID
         * @description PUT /api/asset/:asset_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AssetUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Asset"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete an asset by ID
         * @description DELETE /api/asset/:asset_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/{asset_identity}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover metadata for an asset
         * @description GET /api/asset/:asset_identity/metadata
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AssetMetadataDiscovery"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/{asset_identity}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quote an asset
         * @description GET /api/asset/:asset_identity/quote
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quoter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all quoters
         * @description GET /api/quoter
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["QuotersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quoter/{quoter_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a quoter by id
         * @description GET /api/quoter/:quoter_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    quoter_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Quoter"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enabled vendors
         * @description GET /api/vendor
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["VendorsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all vendors
         * @description GET /api/vendor/all
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["VendorFlagInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/{flag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a vendor flag
         * @description POST /api/vendor/:flag
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    flag: components["schemas"]["VendorFlag"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        /**
         * Disable a vendor flag
         * @description POST /api/vendor/:flag
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    flag: components["schemas"]["VendorFlag"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all vendor flags
         * @description GET /api/health
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** Account */
        Account: {
            /** Format: uint64 */
            account_identity: number;
            name: string;
            networks: number[];
            metadata: components["schemas"]["WalletType"];
        };
        /** AccountBalance */
        AccountBalance: {
            asset_identity: string;
            balance?: string;
            asset_quote?: string;
            balance_quote?: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** AccountBalances */
        AccountBalances: {
            balances: components["schemas"]["AccountBalance"][];
            total_quote?: string;
            /** Format: date-time */
            updated_at: string;
            asset: string;
            errors: string[];
        };
        /** AccountUpdate */
        AccountUpdate: {
            name?: string;
            networks?: number[];
            metadata?: components["schemas"]["WalletType"];
        };
        /** AccountsResponse */
        AccountsResponse: {
            accounts: components["schemas"]["Account"][];
        };
        /** Asset */
        Asset: {
            asset_identity: string;
            asset_name: string;
            asset_symbol: string;
            /** Format: uint8 */
            asset_decimals: number;
            asset_icon_url?: string;
        };
        /** AssetMetadataDiscovery */
        AssetMetadataDiscovery: {
            asset_identity: string;
            options: {
                [key: string]: components["schemas"]["AssetMetadataOption"];
            };
        };
        /** AssetMetadataOption */
        AssetMetadataOption: {
            name?: string;
            symbol?: string;
            /** Format: uint8 */
            decimals?: number;
            icon_url?: string;
        };
        /** AssetUpdate */
        AssetUpdate: {
            asset_name?: string;
            asset_symbol?: string;
            /** Format: uint8 */
            asset_decimals?: number;
            asset_icon_url?: string;
        };
        /** AssetsResponse */
        AssetsResponse: {
            assets: components["schemas"]["Asset"][];
        };
        /** EOAWallet */
        EOAWallet: {
            evm_address: string;
        };
        /** Erc4626QuoterConfig */
        Erc4626QuoterConfig: Record<string, never>;
        /** FixedQuoterConfig */
        FixedQuoterConfig: {
            price: string;
            /** Format: uint8 */
            decimals: number;
            /** Format: uint8 */
            token_in_decimals: number;
            /** Format: uint8 */
            token_out_decimals: number;
        };
        /** Network */
        Network: {
            /**
             * Format: uint64
             * @description evm chain id
             */
            network_identity: number;
            /** @description name, Ethereum Mainnet, Optimism, etc */
            network_name: string;
            /** @description icon url, https://example.com/icon.png, etc */
            network_icon_url?: string;
        };
        /** NetworkEndpoint */
        NetworkEndpoint: {
            /** Format: int32 */
            endpoint_identity: number;
            endpoint_label?: string;
            endpoint_type: string;
            endpoint_url: string;
            endpoint_disabled: boolean;
            /** Format: uint64 */
            network_identity: number;
        };
        /** NetworkEndpointUpdate */
        NetworkEndpointUpdate: {
            endpoint_label?: string;
            endpoint_type?: string;
            endpoint_url?: string;
            endpoint_disabled?: boolean;
        };
        /** NetworkMetadataDiscovery */
        NetworkMetadataDiscovery: {
            /** Format: uint64 */
            network_identity: number;
            options: {
                [key: string]: components["schemas"]["NetworkMetadataOption"];
            };
        };
        /** NetworkMetadataOption */
        NetworkMetadataOption: {
            icon_url?: string;
        };
        /** NetworkUpdate */
        NetworkUpdate: {
            network_name?: string;
            network_icon_url?: string;
        };
        /** NetworksResponse */
        NetworksResponse: {
            networks: components["schemas"]["Network"][];
        };
        /** Quoter */
        Quoter: {
            quoter_identity: string;
            quoter_name: string;
            token_a: string;
            token_b: string;
            config: components["schemas"]["QuoterConfig"];
            enabled: boolean;
            watch: boolean;
        };
        QuoterConfig: components["schemas"]["FixedQuoterConfig"] | components["schemas"]["Erc4626QuoterConfig"] | components["schemas"]["UniswapV2QuoterConfig"] | components["schemas"]["UniswapV3QuoterConfig"];
        /** QuotersResponse */
        QuotersResponse: {
            quoters: components["schemas"]["Quoter"][];
        };
        /** RailgunWallet */
        RailgunWallet: {
            railgun_address: string;
        };
        RpcStatus: components["schemas"]["RpcStatus_Alive"] | components["schemas"]["RpcStatus_Dead"] | components["schemas"]["RpcStatus_Disabled"];
        /** RpcStatusAlive */
        RpcStatusAlive: {
            /** Format: uint64 */
            block_number: number;
            /** Format: uint64 */
            network_identity: number;
            /** Format: uint64 */
            timestamp: number;
        };
        /** RpcStatusDead */
        RpcStatusDead: {
            error: string;
        };
        /** RpcStatusDisabled */
        RpcStatusDisabled: Record<string, never>;
        RpcStatus_Alive: {
            /**
             * @example Alive
             * @enum {string}
             */
            status: "Alive";
        } & components["schemas"]["RpcStatusAlive"];
        RpcStatus_Dead: {
            /**
             * @example Dead
             * @enum {string}
             */
            status: "Dead";
        } & components["schemas"]["RpcStatusDead"];
        RpcStatus_Disabled: {
            /**
             * @example Disabled
             * @enum {string}
             */
            status: "Disabled";
        } & components["schemas"]["RpcStatusDisabled"];
        /** SafeWallet */
        SafeWallet: {
            evm_address: string;
        };
        /** UniswapV2QuoterConfig */
        UniswapV2QuoterConfig: {
            pair_address: string;
        };
        /** UniswapV3QuoterConfig */
        UniswapV3QuoterConfig: {
            pool_address: string;
        };
        /** @enum {string} */
        VendorFlag: "avara_asset_icons" | "zerion_asset_icons" | "smoldapp_asset_icons" | "smoldapp_network_icons" | "safewallet_network_icons" | "safewallet_asset_icons" | "etherscan_asset_icons" | "etherscan_link_tx_hash" | "etherscan_link_address" | "etherscan_link_block" | "etherscan_link_contracts" | "blockscout_asset_icons" | "blockscout_link_tx_hash" | "blockscout_link_address" | "blockscout_link_block" | "blockscout_link_contracts";
        /** VendorFlagInfo */
        VendorFlagInfo: {
            flag: components["schemas"]["VendorFlag"];
            comment: string;
            unfinished: boolean;
        };
        /** VendorFlagInfoResponse */
        VendorFlagInfoResponse: {
            vendors: components["schemas"]["VendorFlagInfo"][];
        };
        /** VendorsResponse */
        VendorsResponse: {
            vendors: components["schemas"]["VendorFlag"][];
        };
        /** ViewWallet */
        ViewWallet: {
            evm_address: string;
        };
        WalletType: components["schemas"]["WalletType_Safe"] | components["schemas"]["WalletType_EOA"] | components["schemas"]["WalletType_View"] | components["schemas"]["WalletType_Railgun"];
        WalletType_EOA: {
            /**
             * @example eoa
             * @enum {string}
             */
            type: "eoa";
        } & components["schemas"]["EOAWallet"];
        WalletType_Railgun: {
            /**
             * @example railgun
             * @enum {string}
             */
            type: "railgun";
        } & components["schemas"]["RailgunWallet"];
        WalletType_Safe: {
            /**
             * @example safe
             * @enum {string}
             */
            type: "safe";
        } & components["schemas"]["SafeWallet"];
        WalletType_View: {
            /**
             * @example view
             * @enum {string}
             */
            type: "view";
        } & components["schemas"]["ViewWallet"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
