/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteRouteImport } from "./routes/settings/route"
import { Route as OnboardingRouteRouteImport } from "./routes/onboarding/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as OnboardingIndexRouteImport } from "./routes/onboarding/index"
import { Route as SettingsVendorsRouteImport } from "./routes/settings/vendors"
import { Route as SettingsQuotersRouteImport } from "./routes/settings/quoters"
import { Route as SettingsNetworksRouteImport } from "./routes/settings/networks"
import { Route as SettingsAssetsRouteImport } from "./routes/settings/assets"
import { Route as OnboardingVendorsRouteImport } from "./routes/onboarding/vendors"
import { Route as OnboardingNetworksRouteImport } from "./routes/onboarding/networks"
import { Route as OnboardingAssetsRouteImport } from "./routes/onboarding/assets"
import { Route as OnboardingAccountsRouteImport } from "./routes/onboarding/accounts"
import { Route as AccNRouteImport } from "./routes/acc/_n"
import { Route as AccAccountRouteRouteImport } from "./routes/acc/$account/route"
import { Route as AccAccountIndexRouteImport } from "./routes/acc/$account/index"
import { Route as AccAccountNewTxRouteImport } from "./routes/acc/$account/new-tx"
import { Route as AccAccountHistoryRouteImport } from "./routes/acc/$account/history"
import { Route as AccAccountAssetsRouteImport } from "./routes/acc/$account/assets"
import { Route as AccAccountSettingsRouteRouteImport } from "./routes/acc/$account/settings/route"
import { Route as AccNNewIndexRouteImport } from "./routes/acc/_n.new/index"
import { Route as AccAccountSettingsIndexRouteImport } from "./routes/acc/$account/settings/index"
import { Route as AccNNewSafeRouteImport } from "./routes/acc/_n.new/safe"
import { Route as AccNNewPrivateKeyRouteImport } from "./routes/acc/_n.new/private-key"
import { Route as AccNNewMnemonicRouteImport } from "./routes/acc/_n.new/mnemonic"
import { Route as AccNImportViewRouteImport } from "./routes/acc/_n.import/view"
import { Route as AccNImportSafeRouteImport } from "./routes/acc/_n.import/safe"
import { Route as AccNImportPrivateKeyRouteImport } from "./routes/acc/_n.import/private-key"
import { Route as AccNImportMnemonicRouteImport } from "./routes/acc/_n.import/mnemonic"
import { Route as AccAccountSettingsDangerRouteImport } from "./routes/acc/$account/settings/danger"
import { Route as AccAccountSettingsAssetsRouteImport } from "./routes/acc/$account/settings/assets"

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const SettingsVendorsRoute = SettingsVendorsRouteImport.update({
  id: "/vendors",
  path: "/vendors",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsQuotersRoute = SettingsQuotersRouteImport.update({
  id: "/quoters",
  path: "/quoters",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsNetworksRoute = SettingsNetworksRouteImport.update({
  id: "/networks",
  path: "/networks",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAssetsRoute = SettingsAssetsRouteImport.update({
  id: "/assets",
  path: "/assets",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const OnboardingVendorsRoute = OnboardingVendorsRouteImport.update({
  id: "/vendors",
  path: "/vendors",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingNetworksRoute = OnboardingNetworksRouteImport.update({
  id: "/networks",
  path: "/networks",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAssetsRoute = OnboardingAssetsRouteImport.update({
  id: "/assets",
  path: "/assets",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAccountsRoute = OnboardingAccountsRouteImport.update({
  id: "/accounts",
  path: "/accounts",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AccNRoute = AccNRouteImport.update({
  id: "/acc/_n",
  path: "/acc",
  getParentRoute: () => rootRouteImport,
} as any)
const AccAccountRouteRoute = AccAccountRouteRouteImport.update({
  id: "/acc/$account",
  path: "/acc/$account",
  getParentRoute: () => rootRouteImport,
} as any)
const AccAccountIndexRoute = AccAccountIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountNewTxRoute = AccAccountNewTxRouteImport.update({
  id: "/new-tx",
  path: "/new-tx",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountHistoryRoute = AccAccountHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountAssetsRoute = AccAccountAssetsRouteImport.update({
  id: "/assets",
  path: "/assets",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountSettingsRouteRoute = AccAccountSettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccNNewIndexRoute = AccNNewIndexRouteImport.update({
  id: "/new/",
  path: "/new/",
  getParentRoute: () => AccNRoute,
} as any)
const AccAccountSettingsIndexRoute = AccAccountSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AccAccountSettingsRouteRoute,
} as any)
const AccNNewSafeRoute = AccNNewSafeRouteImport.update({
  id: "/new/safe",
  path: "/new/safe",
  getParentRoute: () => AccNRoute,
} as any)
const AccNNewPrivateKeyRoute = AccNNewPrivateKeyRouteImport.update({
  id: "/new/private-key",
  path: "/new/private-key",
  getParentRoute: () => AccNRoute,
} as any)
const AccNNewMnemonicRoute = AccNNewMnemonicRouteImport.update({
  id: "/new/mnemonic",
  path: "/new/mnemonic",
  getParentRoute: () => AccNRoute,
} as any)
const AccNImportViewRoute = AccNImportViewRouteImport.update({
  id: "/import/view",
  path: "/import/view",
  getParentRoute: () => AccNRoute,
} as any)
const AccNImportSafeRoute = AccNImportSafeRouteImport.update({
  id: "/import/safe",
  path: "/import/safe",
  getParentRoute: () => AccNRoute,
} as any)
const AccNImportPrivateKeyRoute = AccNImportPrivateKeyRouteImport.update({
  id: "/import/private-key",
  path: "/import/private-key",
  getParentRoute: () => AccNRoute,
} as any)
const AccNImportMnemonicRoute = AccNImportMnemonicRouteImport.update({
  id: "/import/mnemonic",
  path: "/import/mnemonic",
  getParentRoute: () => AccNRoute,
} as any)
const AccAccountSettingsDangerRoute =
  AccAccountSettingsDangerRouteImport.update({
    id: "/danger",
    path: "/danger",
    getParentRoute: () => AccAccountSettingsRouteRoute,
  } as any)
const AccAccountSettingsAssetsRoute =
  AccAccountSettingsAssetsRouteImport.update({
    id: "/assets",
    path: "/assets",
    getParentRoute: () => AccAccountSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRouteRouteWithChildren
  "/settings": typeof SettingsRouteRouteWithChildren
  "/acc/$account": typeof AccAccountRouteRouteWithChildren
  "/acc": typeof AccNRouteWithChildren
  "/onboarding/accounts": typeof OnboardingAccountsRoute
  "/onboarding/assets": typeof OnboardingAssetsRoute
  "/onboarding/networks": typeof OnboardingNetworksRoute
  "/onboarding/vendors": typeof OnboardingVendorsRoute
  "/settings/assets": typeof SettingsAssetsRoute
  "/settings/networks": typeof SettingsNetworksRoute
  "/settings/quoters": typeof SettingsQuotersRoute
  "/settings/vendors": typeof SettingsVendorsRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/acc/$account/settings": typeof AccAccountSettingsRouteRouteWithChildren
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/history": typeof AccAccountHistoryRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/$account/": typeof AccAccountIndexRoute
  "/acc/$account/settings/assets": typeof AccAccountSettingsAssetsRoute
  "/acc/$account/settings/danger": typeof AccAccountSettingsDangerRoute
  "/acc/import/mnemonic": typeof AccNImportMnemonicRoute
  "/acc/import/private-key": typeof AccNImportPrivateKeyRoute
  "/acc/import/safe": typeof AccNImportSafeRoute
  "/acc/import/view": typeof AccNImportViewRoute
  "/acc/new/mnemonic": typeof AccNNewMnemonicRoute
  "/acc/new/private-key": typeof AccNNewPrivateKeyRoute
  "/acc/new/safe": typeof AccNNewSafeRoute
  "/acc/$account/settings/": typeof AccAccountSettingsIndexRoute
  "/acc/new/": typeof AccNNewIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/acc": typeof AccNRouteWithChildren
  "/onboarding/accounts": typeof OnboardingAccountsRoute
  "/onboarding/assets": typeof OnboardingAssetsRoute
  "/onboarding/networks": typeof OnboardingNetworksRoute
  "/onboarding/vendors": typeof OnboardingVendorsRoute
  "/settings/assets": typeof SettingsAssetsRoute
  "/settings/networks": typeof SettingsNetworksRoute
  "/settings/quoters": typeof SettingsQuotersRoute
  "/settings/vendors": typeof SettingsVendorsRoute
  "/onboarding": typeof OnboardingIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/history": typeof AccAccountHistoryRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/$account": typeof AccAccountIndexRoute
  "/acc/$account/settings/assets": typeof AccAccountSettingsAssetsRoute
  "/acc/$account/settings/danger": typeof AccAccountSettingsDangerRoute
  "/acc/import/mnemonic": typeof AccNImportMnemonicRoute
  "/acc/import/private-key": typeof AccNImportPrivateKeyRoute
  "/acc/import/safe": typeof AccNImportSafeRoute
  "/acc/import/view": typeof AccNImportViewRoute
  "/acc/new/mnemonic": typeof AccNNewMnemonicRoute
  "/acc/new/private-key": typeof AccNNewPrivateKeyRoute
  "/acc/new/safe": typeof AccNNewSafeRoute
  "/acc/$account/settings": typeof AccAccountSettingsIndexRoute
  "/acc/new": typeof AccNNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRouteRouteWithChildren
  "/settings": typeof SettingsRouteRouteWithChildren
  "/acc/$account": typeof AccAccountRouteRouteWithChildren
  "/acc/_n": typeof AccNRouteWithChildren
  "/onboarding/accounts": typeof OnboardingAccountsRoute
  "/onboarding/assets": typeof OnboardingAssetsRoute
  "/onboarding/networks": typeof OnboardingNetworksRoute
  "/onboarding/vendors": typeof OnboardingVendorsRoute
  "/settings/assets": typeof SettingsAssetsRoute
  "/settings/networks": typeof SettingsNetworksRoute
  "/settings/quoters": typeof SettingsQuotersRoute
  "/settings/vendors": typeof SettingsVendorsRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/acc/$account/settings": typeof AccAccountSettingsRouteRouteWithChildren
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/history": typeof AccAccountHistoryRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/$account/": typeof AccAccountIndexRoute
  "/acc/$account/settings/assets": typeof AccAccountSettingsAssetsRoute
  "/acc/$account/settings/danger": typeof AccAccountSettingsDangerRoute
  "/acc/_n/import/mnemonic": typeof AccNImportMnemonicRoute
  "/acc/_n/import/private-key": typeof AccNImportPrivateKeyRoute
  "/acc/_n/import/safe": typeof AccNImportSafeRoute
  "/acc/_n/import/view": typeof AccNImportViewRoute
  "/acc/_n/new/mnemonic": typeof AccNNewMnemonicRoute
  "/acc/_n/new/private-key": typeof AccNNewPrivateKeyRoute
  "/acc/_n/new/safe": typeof AccNNewSafeRoute
  "/acc/$account/settings/": typeof AccAccountSettingsIndexRoute
  "/acc/_n/new/": typeof AccNNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/onboarding"
    | "/settings"
    | "/acc/$account"
    | "/acc"
    | "/onboarding/accounts"
    | "/onboarding/assets"
    | "/onboarding/networks"
    | "/onboarding/vendors"
    | "/settings/assets"
    | "/settings/networks"
    | "/settings/quoters"
    | "/settings/vendors"
    | "/onboarding/"
    | "/settings/"
    | "/acc/$account/settings"
    | "/acc/$account/assets"
    | "/acc/$account/history"
    | "/acc/$account/new-tx"
    | "/acc/$account/"
    | "/acc/$account/settings/assets"
    | "/acc/$account/settings/danger"
    | "/acc/import/mnemonic"
    | "/acc/import/private-key"
    | "/acc/import/safe"
    | "/acc/import/view"
    | "/acc/new/mnemonic"
    | "/acc/new/private-key"
    | "/acc/new/safe"
    | "/acc/$account/settings/"
    | "/acc/new/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/acc"
    | "/onboarding/accounts"
    | "/onboarding/assets"
    | "/onboarding/networks"
    | "/onboarding/vendors"
    | "/settings/assets"
    | "/settings/networks"
    | "/settings/quoters"
    | "/settings/vendors"
    | "/onboarding"
    | "/settings"
    | "/acc/$account/assets"
    | "/acc/$account/history"
    | "/acc/$account/new-tx"
    | "/acc/$account"
    | "/acc/$account/settings/assets"
    | "/acc/$account/settings/danger"
    | "/acc/import/mnemonic"
    | "/acc/import/private-key"
    | "/acc/import/safe"
    | "/acc/import/view"
    | "/acc/new/mnemonic"
    | "/acc/new/private-key"
    | "/acc/new/safe"
    | "/acc/$account/settings"
    | "/acc/new"
  id:
    | "__root__"
    | "/"
    | "/onboarding"
    | "/settings"
    | "/acc/$account"
    | "/acc/_n"
    | "/onboarding/accounts"
    | "/onboarding/assets"
    | "/onboarding/networks"
    | "/onboarding/vendors"
    | "/settings/assets"
    | "/settings/networks"
    | "/settings/quoters"
    | "/settings/vendors"
    | "/onboarding/"
    | "/settings/"
    | "/acc/$account/settings"
    | "/acc/$account/assets"
    | "/acc/$account/history"
    | "/acc/$account/new-tx"
    | "/acc/$account/"
    | "/acc/$account/settings/assets"
    | "/acc/$account/settings/danger"
    | "/acc/_n/import/mnemonic"
    | "/acc/_n/import/private-key"
    | "/acc/_n/import/safe"
    | "/acc/_n/import/view"
    | "/acc/_n/new/mnemonic"
    | "/acc/_n/new/private-key"
    | "/acc/_n/new/safe"
    | "/acc/$account/settings/"
    | "/acc/_n/new/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AccAccountRouteRoute: typeof AccAccountRouteRouteWithChildren
  AccNRoute: typeof AccNRouteWithChildren
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/onboarding/": {
      id: "/onboarding/"
      path: "/"
      fullPath: "/onboarding/"
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/settings/vendors": {
      id: "/settings/vendors"
      path: "/vendors"
      fullPath: "/settings/vendors"
      preLoaderRoute: typeof SettingsVendorsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/quoters": {
      id: "/settings/quoters"
      path: "/quoters"
      fullPath: "/settings/quoters"
      preLoaderRoute: typeof SettingsQuotersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/networks": {
      id: "/settings/networks"
      path: "/networks"
      fullPath: "/settings/networks"
      preLoaderRoute: typeof SettingsNetworksRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/assets": {
      id: "/settings/assets"
      path: "/assets"
      fullPath: "/settings/assets"
      preLoaderRoute: typeof SettingsAssetsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/onboarding/vendors": {
      id: "/onboarding/vendors"
      path: "/vendors"
      fullPath: "/onboarding/vendors"
      preLoaderRoute: typeof OnboardingVendorsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/onboarding/networks": {
      id: "/onboarding/networks"
      path: "/networks"
      fullPath: "/onboarding/networks"
      preLoaderRoute: typeof OnboardingNetworksRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/onboarding/assets": {
      id: "/onboarding/assets"
      path: "/assets"
      fullPath: "/onboarding/assets"
      preLoaderRoute: typeof OnboardingAssetsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/onboarding/accounts": {
      id: "/onboarding/accounts"
      path: "/accounts"
      fullPath: "/onboarding/accounts"
      preLoaderRoute: typeof OnboardingAccountsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/acc/_n": {
      id: "/acc/_n"
      path: "/acc"
      fullPath: "/acc"
      preLoaderRoute: typeof AccNRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/$account": {
      id: "/acc/$account"
      path: "/acc/$account"
      fullPath: "/acc/$account"
      preLoaderRoute: typeof AccAccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/$account/": {
      id: "/acc/$account/"
      path: "/"
      fullPath: "/acc/$account/"
      preLoaderRoute: typeof AccAccountIndexRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/new-tx": {
      id: "/acc/$account/new-tx"
      path: "/new-tx"
      fullPath: "/acc/$account/new-tx"
      preLoaderRoute: typeof AccAccountNewTxRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/history": {
      id: "/acc/$account/history"
      path: "/history"
      fullPath: "/acc/$account/history"
      preLoaderRoute: typeof AccAccountHistoryRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/assets": {
      id: "/acc/$account/assets"
      path: "/assets"
      fullPath: "/acc/$account/assets"
      preLoaderRoute: typeof AccAccountAssetsRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/settings": {
      id: "/acc/$account/settings"
      path: "/settings"
      fullPath: "/acc/$account/settings"
      preLoaderRoute: typeof AccAccountSettingsRouteRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/_n/new/": {
      id: "/acc/_n/new/"
      path: "/new"
      fullPath: "/acc/new/"
      preLoaderRoute: typeof AccNNewIndexRouteImport
      parentRoute: typeof AccNRoute
    }
    "/acc/$account/settings/": {
      id: "/acc/$account/settings/"
      path: "/"
      fullPath: "/acc/$account/settings/"
      preLoaderRoute: typeof AccAccountSettingsIndexRouteImport
      parentRoute: typeof AccAccountSettingsRouteRoute
    }
    "/acc/_n/new/safe": {
      id: "/acc/_n/new/safe"
      path: "/new/safe"
      fullPath: "/acc/new/safe"
      preLoaderRoute: typeof AccNNewSafeRouteImport
      parentRoute: typeof AccNRoute
    }
    "/acc/_n/new/private-key": {
      id: "/acc/_n/new/private-key"
      path: "/new/private-key"
      fullPath: "/acc/new/private-key"
      preLoaderRoute: typeof AccNNewPrivateKeyRouteImport
      parentRoute: typeof AccNRoute
    }
    "/acc/_n/new/mnemonic": {
      id: "/acc/_n/new/mnemonic"
      path: "/new/mnemonic"
      fullPath: "/acc/new/mnemonic"
      preLoaderRoute: typeof AccNNewMnemonicRouteImport
      parentRoute: typeof AccNRoute
    }
    "/acc/_n/import/view": {
      id: "/acc/_n/import/view"
      path: "/import/view"
      fullPath: "/acc/import/view"
      preLoaderRoute: typeof AccNImportViewRouteImport
      parentRoute: typeof AccNRoute
    }
    "/acc/_n/import/safe": {
      id: "/acc/_n/import/safe"
      path: "/import/safe"
      fullPath: "/acc/import/safe"
      preLoaderRoute: typeof AccNImportSafeRouteImport
      parentRoute: typeof AccNRoute
    }
    "/acc/_n/import/private-key": {
      id: "/acc/_n/import/private-key"
      path: "/import/private-key"
      fullPath: "/acc/import/private-key"
      preLoaderRoute: typeof AccNImportPrivateKeyRouteImport
      parentRoute: typeof AccNRoute
    }
    "/acc/_n/import/mnemonic": {
      id: "/acc/_n/import/mnemonic"
      path: "/import/mnemonic"
      fullPath: "/acc/import/mnemonic"
      preLoaderRoute: typeof AccNImportMnemonicRouteImport
      parentRoute: typeof AccNRoute
    }
    "/acc/$account/settings/danger": {
      id: "/acc/$account/settings/danger"
      path: "/danger"
      fullPath: "/acc/$account/settings/danger"
      preLoaderRoute: typeof AccAccountSettingsDangerRouteImport
      parentRoute: typeof AccAccountSettingsRouteRoute
    }
    "/acc/$account/settings/assets": {
      id: "/acc/$account/settings/assets"
      path: "/assets"
      fullPath: "/acc/$account/settings/assets"
      preLoaderRoute: typeof AccAccountSettingsAssetsRouteImport
      parentRoute: typeof AccAccountSettingsRouteRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingAccountsRoute: typeof OnboardingAccountsRoute
  OnboardingAssetsRoute: typeof OnboardingAssetsRoute
  OnboardingNetworksRoute: typeof OnboardingNetworksRoute
  OnboardingVendorsRoute: typeof OnboardingVendorsRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAccountsRoute: OnboardingAccountsRoute,
  OnboardingAssetsRoute: OnboardingAssetsRoute,
  OnboardingNetworksRoute: OnboardingNetworksRoute,
  OnboardingVendorsRoute: OnboardingVendorsRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAssetsRoute: typeof SettingsAssetsRoute
  SettingsNetworksRoute: typeof SettingsNetworksRoute
  SettingsQuotersRoute: typeof SettingsQuotersRoute
  SettingsVendorsRoute: typeof SettingsVendorsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAssetsRoute: SettingsAssetsRoute,
  SettingsNetworksRoute: SettingsNetworksRoute,
  SettingsQuotersRoute: SettingsQuotersRoute,
  SettingsVendorsRoute: SettingsVendorsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AccAccountSettingsRouteRouteChildren {
  AccAccountSettingsAssetsRoute: typeof AccAccountSettingsAssetsRoute
  AccAccountSettingsDangerRoute: typeof AccAccountSettingsDangerRoute
  AccAccountSettingsIndexRoute: typeof AccAccountSettingsIndexRoute
}

const AccAccountSettingsRouteRouteChildren: AccAccountSettingsRouteRouteChildren =
  {
    AccAccountSettingsAssetsRoute: AccAccountSettingsAssetsRoute,
    AccAccountSettingsDangerRoute: AccAccountSettingsDangerRoute,
    AccAccountSettingsIndexRoute: AccAccountSettingsIndexRoute,
  }

const AccAccountSettingsRouteRouteWithChildren =
  AccAccountSettingsRouteRoute._addFileChildren(
    AccAccountSettingsRouteRouteChildren,
  )

interface AccAccountRouteRouteChildren {
  AccAccountSettingsRouteRoute: typeof AccAccountSettingsRouteRouteWithChildren
  AccAccountAssetsRoute: typeof AccAccountAssetsRoute
  AccAccountHistoryRoute: typeof AccAccountHistoryRoute
  AccAccountNewTxRoute: typeof AccAccountNewTxRoute
  AccAccountIndexRoute: typeof AccAccountIndexRoute
}

const AccAccountRouteRouteChildren: AccAccountRouteRouteChildren = {
  AccAccountSettingsRouteRoute: AccAccountSettingsRouteRouteWithChildren,
  AccAccountAssetsRoute: AccAccountAssetsRoute,
  AccAccountHistoryRoute: AccAccountHistoryRoute,
  AccAccountNewTxRoute: AccAccountNewTxRoute,
  AccAccountIndexRoute: AccAccountIndexRoute,
}

const AccAccountRouteRouteWithChildren = AccAccountRouteRoute._addFileChildren(
  AccAccountRouteRouteChildren,
)

interface AccNRouteChildren {
  AccNImportMnemonicRoute: typeof AccNImportMnemonicRoute
  AccNImportPrivateKeyRoute: typeof AccNImportPrivateKeyRoute
  AccNImportSafeRoute: typeof AccNImportSafeRoute
  AccNImportViewRoute: typeof AccNImportViewRoute
  AccNNewMnemonicRoute: typeof AccNNewMnemonicRoute
  AccNNewPrivateKeyRoute: typeof AccNNewPrivateKeyRoute
  AccNNewSafeRoute: typeof AccNNewSafeRoute
  AccNNewIndexRoute: typeof AccNNewIndexRoute
}

const AccNRouteChildren: AccNRouteChildren = {
  AccNImportMnemonicRoute: AccNImportMnemonicRoute,
  AccNImportPrivateKeyRoute: AccNImportPrivateKeyRoute,
  AccNImportSafeRoute: AccNImportSafeRoute,
  AccNImportViewRoute: AccNImportViewRoute,
  AccNNewMnemonicRoute: AccNNewMnemonicRoute,
  AccNNewPrivateKeyRoute: AccNNewPrivateKeyRoute,
  AccNNewSafeRoute: AccNNewSafeRoute,
  AccNNewIndexRoute: AccNNewIndexRoute,
}

const AccNRouteWithChildren = AccNRoute._addFileChildren(AccNRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AccAccountRouteRoute: AccAccountRouteRouteWithChildren,
  AccNRoute: AccNRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
