// Generated by ts-to-zod
import { z } from "zod";
import { type DecodedCall } from "./bindings.gen";

export const rpcErrorKindSchema = z.union([z.literal("invalid_input"), z.literal("not_found"), z.literal("conflict"), z.literal("unavailable"), z.literal("internal")]);

export const rpcErrorDataSchema = z.object({
    kind: rpcErrorKindSchema,
    message: z.string()
});

export const rpcErrorObjectSchema = z.object({
    code: z.number(),
    message: z.string(),
    data: rpcErrorDataSchema.nullish().transform(value => value ?? undefined)
});

export const walletTypeSchema = z.union([z.object({
        type: z.literal("safe"),
        evm_address: z.string()
    }), z.object({
        type: z.literal("eoa"),
        evm_address: z.string()
    }), z.object({
        type: z.literal("view"),
        evm_address: z.string()
    }), z.object({
        type: z.literal("railgun"),
        railgun_address: z.string()
    })]);

export const accountSchema = z.object({
    account_identity: z.number(),
    name: z.string(),
    networks: z.array(z.number()),
    metadata: walletTypeSchema,
    group_id: z.number().nullish().transform(value => value ?? undefined),
    display_order: z.number()
});

export const accountUpdateSchema = z.object({
    name: z.string().nullish().transform(value => value ?? undefined),
    networks: z.array(z.number()).nullish().transform(value => value ?? undefined),
    metadata: walletTypeSchema.nullish().transform(value => value ?? undefined)
});

export const accountGroupSchema = z.object({
    group_identity: z.number(),
    name: z.string(),
    display_order: z.number()
});

export const accountGroupCreateSchema = z.object({
    name: z.string()
});

export const accountGroupUpdateSchema = z.object({
    name: z.string().nullish().transform(value => value ?? undefined)
});

export const accountLayoutSchema = z.object({
    groups: z.array(accountGroupSchema),
    accounts: z.array(accountSchema)
});

export const accountLayoutUpdateSchema = z.object({
    groups: z.array(z.object({
        group_identity: z.number(),
        name: z.string(),
        display_order: z.number()
    })),
    accounts: z.array(z.object({
        account_identity: z.number(),
        group_id: z.number().nullish().transform(value => value ?? undefined),
        display_order: z.number()
    }))
});

export const accountBalanceSchema = z.object({
    asset_identity: z.string(),
    balance: z.string().nullish().transform(value => value ?? undefined),
    balance_error: z.string().nullish().transform(value => value ?? undefined),
    asset_quote: z.string().nullish().transform(value => value ?? undefined),
    asset_quote_error: z.string().nullish().transform(value => value ?? undefined),
    asset_24h_quote: z.string().nullish().transform(value => value ?? undefined),
    asset_24h_quote_error: z.string().nullish().transform(value => value ?? undefined),
    balance_quote: z.string().nullish().transform(value => value ?? undefined),
    balance_quote_error: z.string().nullish().transform(value => value ?? undefined),
    updated_at: z.string()
});

export const accountBalancesSchema = z.object({
    balances: z.array(accountBalanceSchema),
    total_quote: z.string().nullish().transform(value => value ?? undefined),
    updated_at: z.string(),
    asset: z.string(),
    errors: z.array(z.string())
});

export const assetSchema = z.object({
    asset_identity: z.string(),
    asset_name: z.string(),
    asset_symbol: z.string(),
    asset_decimals: z.number(),
    asset_icon_url: z.string().nullish().transform(value => value ?? undefined)
});

export const assetUpdateSchema = z.object({
    asset_name: z.string().nullish().transform(value => value ?? undefined),
    asset_symbol: z.string().nullish().transform(value => value ?? undefined),
    asset_decimals: z.number().nullish().transform(value => value ?? undefined),
    asset_icon_url: z.string().nullish().transform(value => value ?? undefined)
});

export const assetMetadataOptionSchema = z.object({
    name: z.string().nullish().transform(value => value ?? undefined),
    symbol: z.string().nullish().transform(value => value ?? undefined),
    decimals: z.number().nullish().transform(value => value ?? undefined),
    icon_url: z.string().nullish().transform(value => value ?? undefined)
});

export const assetMetadataDiscoverySchema = z.object({
    asset_identity: z.string(),
    options: z.record(z.string(), assetMetadataOptionSchema)
});

export const networkSchema = z.object({
    network_identity: z.number(),
    network_name: z.string(),
    network_icon_url: z.string().nullish().transform(value => value ?? undefined)
});

export const networkUpdateSchema = z.object({
    network_name: z.string().nullish().transform(value => value ?? undefined),
    network_icon_url: z.string().nullish().transform(value => value ?? undefined)
});

export const networkEndpointSchema = z.object({
    endpoint_identity: z.number(),
    endpoint_label: z.string().nullish().transform(value => value ?? undefined),
    endpoint_type: z.string(),
    endpoint_url: z.string(),
    endpoint_disabled: z.boolean(),
    network_identity: z.number()
});

export const networkEndpointUpdateSchema = z.object({
    endpoint_label: z.string().nullish().transform(value => value ?? undefined),
    endpoint_type: z.string().nullish().transform(value => value ?? undefined),
    endpoint_url: z.string().nullish().transform(value => value ?? undefined),
    endpoint_disabled: z.boolean().nullish().transform(value => value ?? undefined)
});

export const networkMetadataDiscoverySchema = z.object({
    network_identity: z.number(),
    options: z.record(z.string(), z.object({
        icon_url: z.string().nullish().transform(value => value ?? undefined)
    }))
});

export const rpcMethodStatsSchema = z.object({
    method: z.string(),
    total: z.number(),
    errors: z.number()
});

export const rpcCallSampleSchema = z.object({
    timestamp: z.number(),
    methods: z.array(z.string()),
    request_count: z.number(),
    duration_ms: z.number(),
    success: z.boolean(),
    error: z.string().nullish().transform(value => value ?? undefined)
});

export const rpcEndpointStatsSchema = z.object({
    in_flight: z.number(),
    queued: z.number(),
    max_in_flight: z.number(),
    total_requests: z.number(),
    total_errors: z.number(),
    total_rate_limited: z.number(),
    average_duration_ms: z.number(),
    connection_attempts: z.number(),
    connection_successes: z.number(),
    connection_failures: z.number(),
    last_request_at: z.number().nullish().transform(value => value ?? undefined),
    last_error_at: z.number().nullish().transform(value => value ?? undefined),
    last_connected_at: z.number().nullish().transform(value => value ?? undefined),
    last_error: z.string().nullish().transform(value => value ?? undefined),
    methods: z.array(rpcMethodStatsSchema),
    recent: z.array(rpcCallSampleSchema)
});

export const rpcPoolStatsSchema = z.object({
    network_identity: z.number(),
    endpoint_count: z.number(),
    alive_count: z.number(),
    dead_count: z.number(),
    disabled_count: z.number(),
    in_flight: z.number(),
    queued: z.number(),
    total_requests: z.number(),
    total_errors: z.number(),
    endpoints: z.array(z.object({
        endpoint_identity: z.number(),
        status: z.string(),
        in_flight: z.number(),
        queued: z.number(),
        total_requests: z.number(),
        total_errors: z.number()
    }))
});

export const rpcStatusSchema = z.union([z.object({
        status: z.literal("Alive"),
        block_number: z.number(),
        network_identity: z.number(),
        timestamp: z.number(),
        rpc: rpcEndpointStatsSchema
    }), z.object({
        status: z.literal("Dead"),
        error: z.string(),
        rpc: rpcEndpointStatsSchema
    }), z.object({
        status: z.literal("Disabled"),
        rpc: rpcEndpointStatsSchema
    })]);

export const quoterConfigSchema = z.union([z.object({
        type: z.literal("fixed"),
        price: z.string(),
        decimals: z.number(),
        token_in_decimals: z.number(),
        token_out_decimals: z.number()
    }), z.object({
        type: z.literal("erc4626")
    }), z.object({
        type: z.literal("uniswap_v2"),
        pair_address: z.string()
    }), z.object({
        type: z.literal("uniswap_v3"),
        pool_address: z.string()
    })]);

export const quoterSchema = z.object({
    quoter_identity: z.string(),
    quoter_name: z.string(),
    token_a: z.string(),
    token_b: z.string(),
    config: quoterConfigSchema,
    enabled: z.boolean(),
    watch: z.boolean()
});

export const quoterCreateSchema = quoterSchema.omit({ "quoter_identity": true });

export const quoterUpdateSchema = quoterCreateSchema.partial();

export const uniswapV2PairSchema = z.object({
    pair_address: z.string(),
    reserve_0: z.string().nullish().transform(value => value ?? undefined),
    reserve_1: z.string().nullish().transform(value => value ?? undefined)
});

export const uniswapV3PoolSchema = z.object({
    pool_address: z.string(),
    fee: z.number(),
    reserve_0: z.string().nullish().transform(value => value ?? undefined),
    reserve_1: z.string().nullish().transform(value => value ?? undefined)
});

export const quoterDiscoverySchema = z.object({
    token_a: z.string(),
    token_b: z.string().nullish().transform(value => value ?? undefined)
});

export const quoterDiscoveryResponseSchema = z.object({
    erc4626: z.string().nullish().transform(value => value ?? undefined),
    uniswap_v2: uniswapV2PairSchema.nullish().transform(value => value ?? undefined),
    uniswap_v3: z.array(uniswapV3PoolSchema).nullish().transform(value => value ?? undefined)
});

export const vendorFlagSchema = z.union([z.literal("avara_asset_icons"), z.literal("zerion_asset_icons"), z.literal("smoldapp_asset_icons"), z.literal("smoldapp_network_icons"), z.literal("safewallet_network_icons"), z.literal("safewallet_asset_icons"), z.literal("safewallet_transactions_api"), z.literal("etherscan_asset_icons"), z.literal("etherscan_link_tx_hash"), z.literal("etherscan_link_address"), z.literal("etherscan_link_block"), z.literal("etherscan_link_contracts"), z.literal("blockscout_asset_icons"), z.literal("blockscout_link_tx_hash"), z.literal("blockscout_link_address"), z.literal("blockscout_link_block"), z.literal("blockscout_link_contracts")]);

export const vendorFlagInfoSchema = z.object({
    flag: vendorFlagSchema,
    comment: z.string(),
    unfinished: z.boolean()
});

export const decodedContractSchema = z.object({
    address: z.string(),
    verified_name: z.string().nullish().transform(value => value ?? undefined),
    proxy: z.object({
        proxy_type: z.string().nullish().transform(value => value ?? undefined),
        implementation: z.string(),
        implementation_name: z.string().nullish().transform(value => value ?? undefined)
    }).nullish().transform(value => value ?? undefined)
});

export const decodedParamSchema = z.object({
    name: z.string().nullish().transform(value => value ?? undefined),
    ty: z.string(),
    value: z.unknown()
});

export const decodedSchema = z.union([z.object({
        kind: z.literal("verified"),
        contract: decodedContractSchema,
        selector: z.string(),
        function: z.string(),
        signature: z.string(),
        params: z.array(decodedParamSchema)
    }), z.object({
        kind: z.literal("signature_fallback"),
        contract: decodedContractSchema.nullish().transform(value => value ?? undefined),
        selector: z.string(),
        candidates: z.array(z.string())
    }), z.object({
        kind: z.literal("raw"),
        data: z.string()
    })]);

export const decodedCallSchema: z.ZodSchema<DecodedCall> = z.lazy(() => z.object({
    from: z.string().nullish().transform(value => value ?? undefined),
    to: z.string(),
    value: z.string(),
    operation: z.string().nullish().transform(value => value ?? undefined),
    data: z.string(),
    selector: z.string().nullish().transform(value => value ?? undefined),
    decoded: decodedSchema,
    subcalls: z.array(decodedCallSchema)
}));

export const txSchema = z.object({
    network_identity: z.number(),
    tx_hash: z.string().nullish().transform(value => value ?? undefined),
    from: z.string().nullish().transform(value => value ?? undefined),
    to: z.string().nullish().transform(value => value ?? undefined),
    data: z.string().nullish().transform(value => value ?? undefined),
    value: z.string(),
    decoded: decodedCallSchema.nullish().transform(value => value ?? undefined),
    extra: z.object({
        safe_wallet: z.object({
            nonce: z.number().nullish().transform(value => value ?? undefined),
            execution_date: z.string().nullish().transform(value => value ?? undefined),
            safe_tx_hash: z.string().nullish().transform(value => value ?? undefined),
            proposer: z.string().nullish().transform(value => value ?? undefined),
            executor: z.string().nullish().transform(value => value ?? undefined),
            is_successful: z.boolean().nullish().transform(value => value ?? undefined),
            is_executed: z.boolean().nullish().transform(value => value ?? undefined),
            origin: z.string().nullish().transform(value => value ?? undefined),
            extra: z.unknown()
        }).nullish().transform(value => value ?? undefined)
    })
});

export const decodeTransactionRequestSchema = z.object({
    from: z.string().nullish().transform(value => value ?? undefined),
    to: z.string(),
    value: z.string().nullish().transform(value => value ?? undefined),
    data: z.string().nullish().transform(value => value ?? undefined)
});

export const decodeTransactionResponseSchema = z.object({
    call: decodedCallSchema
});

export const simulateTransactionRequestSchema = decodeTransactionRequestSchema;

export const simulateTransactionResponseSchema = decodeTransactionResponseSchema;

export const deriveMnemonicResultSchema = z.object({
    path: z.string(),
    address: z.string()
});
