/* Generated from the Rust RPC contract. Do not edit. */

import {
    accountAssetAddRpcResultSchema,
    accountAssetBalanceRpcResultSchema,
    accountAssetListRpcResultSchema,
    accountAssetRemoveRpcResultSchema,
    accountBalanceListRpcResultSchema,
    accountCreateRpcResultSchema,
    accountDeleteRpcResultSchema,
    accountDerivationDefaultPathRpcResultSchema,
    accountDerivationFromMnemonicRpcResultSchema,
    accountDerivationFromPrivateKeyRpcResultSchema,
    accountGetRpcResultSchema,
    accountGroupCreateRpcResultSchema,
    accountGroupDeleteRpcResultSchema,
    accountGroupUpdateRpcResultSchema,
    accountLayoutGetRpcResultSchema,
    accountLayoutUpdateRpcResultSchema,
    accountListRpcResultSchema,
    accountMnemonicGenerateRpcResultSchema,
    accountNextIdentityRpcResultSchema,
    accountTransactionListRpcResultSchema,
    accountTransactionPendingRpcResultSchema,
    accountUpdateRpcResultSchema,
    assetCreateRpcResultSchema,
    assetDeleteRpcResultSchema,
    assetDiscoverMetadataRpcResultSchema,
    assetGetRpcResultSchema,
    assetIconRpcResultSchema,
    assetListRpcResultSchema,
    assetQuoteRpcResultSchema,
    assetUpdateRpcResultSchema,
    ensResolveRpcResultSchema,
    ensReverseRpcResultSchema,
    networkCreateRpcResultSchema,
    networkDeleteRpcResultSchema,
    networkDiscoverMetadataRpcResultSchema,
    endpointCreateRpcResultSchema,
    endpointDeleteRpcResultSchema,
    endpointGetRpcResultSchema,
    endpointListRpcResultSchema,
    endpointNextIdentityRpcResultSchema,
    endpointStatusRpcResultSchema,
    endpointUpdateRpcResultSchema,
    networkGetRpcResultSchema,
    networkListRpcResultSchema,
    networkListPresetsRpcResultSchema,
    networkRpcStatsRpcResultSchema,
    networkUpdateRpcResultSchema,
    quoterCreateRpcResultSchema,
    quoterDiscoverRpcResultSchema,
    quoterGetRpcResultSchema,
    quoterListRpcResultSchema,
    quoterUpdateRpcResultSchema,
    systemPingRpcResultSchema,
    transactionDecodeRpcResultSchema,
    transactionSimulateRpcResultSchema,
    vendorDisableRpcResultSchema,
    vendorEnableRpcResultSchema,
    vendorListAllRpcResultSchema,
    vendorListEnabledRpcResultSchema,
} from "./bindings.zod.gen";
import { createRpcClient } from "./rpc-transport";
import type { RpcMethodName, RpcParams, RpcResult } from "./rpc-contract.gen";

export const rpcTransport = createRpcClient();
const empty = {};

export const rpc = {
    accountAssetAdd: (params: RpcParams<"account.asset.add">): Promise<RpcResult<"account.asset.add">> => rpcTransport.call("account.asset.add", params, value => accountAssetAddRpcResultSchema.parse(value)),
    accountAssetBalance: (params: RpcParams<"account.asset.balance">): Promise<RpcResult<"account.asset.balance">> => rpcTransport.call("account.asset.balance", params, value => accountAssetBalanceRpcResultSchema.parse(value)),
    accountAssetList: (params: RpcParams<"account.asset.list">): Promise<RpcResult<"account.asset.list">> => rpcTransport.call("account.asset.list", params, value => accountAssetListRpcResultSchema.parse(value)),
    accountAssetRemove: (params: RpcParams<"account.asset.remove">): Promise<RpcResult<"account.asset.remove">> => rpcTransport.call("account.asset.remove", params, value => accountAssetRemoveRpcResultSchema.parse(value)),
    accountBalanceList: (params: RpcParams<"account.balance.list">): Promise<RpcResult<"account.balance.list">> => rpcTransport.call("account.balance.list", params, value => accountBalanceListRpcResultSchema.parse(value)),
    accountCreate: (params: RpcParams<"account.create">): Promise<RpcResult<"account.create">> => rpcTransport.call("account.create", params, value => accountCreateRpcResultSchema.parse(value)),
    accountDelete: (params: RpcParams<"account.delete">): Promise<RpcResult<"account.delete">> => rpcTransport.call("account.delete", params, value => accountDeleteRpcResultSchema.parse(value)),
    accountDerivationDefaultPath: (): Promise<RpcResult<"account.derivation.defaultPath">> => rpcTransport.call("account.derivation.defaultPath", empty, value => accountDerivationDefaultPathRpcResultSchema.parse(value)),
    accountDerivationFromMnemonic: (params: RpcParams<"account.derivation.fromMnemonic">): Promise<RpcResult<"account.derivation.fromMnemonic">> => rpcTransport.call("account.derivation.fromMnemonic", params, value => accountDerivationFromMnemonicRpcResultSchema.parse(value)),
    accountDerivationFromPrivateKey: (params: RpcParams<"account.derivation.fromPrivateKey">): Promise<RpcResult<"account.derivation.fromPrivateKey">> => rpcTransport.call("account.derivation.fromPrivateKey", params, value => accountDerivationFromPrivateKeyRpcResultSchema.parse(value)),
    accountGet: (params: RpcParams<"account.get">): Promise<RpcResult<"account.get">> => rpcTransport.call("account.get", params, value => accountGetRpcResultSchema.parse(value)),
    accountGroupCreate: (params: RpcParams<"account.group.create">): Promise<RpcResult<"account.group.create">> => rpcTransport.call("account.group.create", params, value => accountGroupCreateRpcResultSchema.parse(value)),
    accountGroupDelete: (params: RpcParams<"account.group.delete">): Promise<RpcResult<"account.group.delete">> => rpcTransport.call("account.group.delete", params, value => accountGroupDeleteRpcResultSchema.parse(value)),
    accountGroupUpdate: (params: RpcParams<"account.group.update">): Promise<RpcResult<"account.group.update">> => rpcTransport.call("account.group.update", params, value => accountGroupUpdateRpcResultSchema.parse(value)),
    accountLayoutGet: (): Promise<RpcResult<"account.layout.get">> => rpcTransport.call("account.layout.get", empty, value => accountLayoutGetRpcResultSchema.parse(value)),
    accountLayoutUpdate: (params: RpcParams<"account.layout.update">): Promise<RpcResult<"account.layout.update">> => rpcTransport.call("account.layout.update", params, value => accountLayoutUpdateRpcResultSchema.parse(value)),
    accountList: (): Promise<RpcResult<"account.list">> => rpcTransport.call("account.list", empty, value => accountListRpcResultSchema.parse(value)),
    accountMnemonicGenerate: (): Promise<RpcResult<"account.mnemonic.generate">> => rpcTransport.call("account.mnemonic.generate", empty, value => accountMnemonicGenerateRpcResultSchema.parse(value)),
    accountNextIdentity: (): Promise<RpcResult<"account.nextIdentity">> => rpcTransport.call("account.nextIdentity", empty, value => accountNextIdentityRpcResultSchema.parse(value)),
    accountTransactionList: (params: RpcParams<"account.transaction.list">): Promise<RpcResult<"account.transaction.list">> => rpcTransport.call("account.transaction.list", params, value => accountTransactionListRpcResultSchema.parse(value)),
    accountTransactionPending: (params: RpcParams<"account.transaction.pending">): Promise<RpcResult<"account.transaction.pending">> => rpcTransport.call("account.transaction.pending", params, value => accountTransactionPendingRpcResultSchema.parse(value)),
    accountUpdate: (params: RpcParams<"account.update">): Promise<RpcResult<"account.update">> => rpcTransport.call("account.update", params, value => accountUpdateRpcResultSchema.parse(value)),
    assetCreate: (params: RpcParams<"asset.create">): Promise<RpcResult<"asset.create">> => rpcTransport.call("asset.create", params, value => assetCreateRpcResultSchema.parse(value)),
    assetDelete: (params: RpcParams<"asset.delete">): Promise<RpcResult<"asset.delete">> => rpcTransport.call("asset.delete", params, value => assetDeleteRpcResultSchema.parse(value)),
    assetDiscoverMetadata: (params: RpcParams<"asset.discoverMetadata">): Promise<RpcResult<"asset.discoverMetadata">> => rpcTransport.call("asset.discoverMetadata", params, value => assetDiscoverMetadataRpcResultSchema.parse(value)),
    assetGet: (params: RpcParams<"asset.get">): Promise<RpcResult<"asset.get">> => rpcTransport.call("asset.get", params, value => assetGetRpcResultSchema.parse(value)),
    assetIcon: (params: RpcParams<"asset.icon">): Promise<RpcResult<"asset.icon">> => rpcTransport.call("asset.icon", params, value => assetIconRpcResultSchema.parse(value)),
    assetList: (): Promise<RpcResult<"asset.list">> => rpcTransport.call("asset.list", empty, value => assetListRpcResultSchema.parse(value)),
    assetQuote: (params: RpcParams<"asset.quote">): Promise<RpcResult<"asset.quote">> => rpcTransport.call("asset.quote", params, value => assetQuoteRpcResultSchema.parse(value)),
    assetUpdate: (params: RpcParams<"asset.update">): Promise<RpcResult<"asset.update">> => rpcTransport.call("asset.update", params, value => assetUpdateRpcResultSchema.parse(value)),
    ensResolve: (params: RpcParams<"ens.resolve">): Promise<RpcResult<"ens.resolve">> => rpcTransport.call("ens.resolve", params, value => ensResolveRpcResultSchema.parse(value)),
    ensReverse: (params: RpcParams<"ens.reverse">): Promise<RpcResult<"ens.reverse">> => rpcTransport.call("ens.reverse", params, value => ensReverseRpcResultSchema.parse(value)),
    networkCreate: (params: RpcParams<"network.create">): Promise<RpcResult<"network.create">> => rpcTransport.call("network.create", params, value => networkCreateRpcResultSchema.parse(value)),
    networkDelete: (params: RpcParams<"network.delete">): Promise<RpcResult<"network.delete">> => rpcTransport.call("network.delete", params, value => networkDeleteRpcResultSchema.parse(value)),
    networkDiscoverMetadata: (params: RpcParams<"network.discoverMetadata">): Promise<RpcResult<"network.discoverMetadata">> => rpcTransport.call("network.discoverMetadata", params, value => networkDiscoverMetadataRpcResultSchema.parse(value)),
    endpointCreate: (params: RpcParams<"network.endpoint.create">): Promise<RpcResult<"network.endpoint.create">> => rpcTransport.call("network.endpoint.create", params, value => endpointCreateRpcResultSchema.parse(value)),
    endpointDelete: (params: RpcParams<"network.endpoint.delete">): Promise<RpcResult<"network.endpoint.delete">> => rpcTransport.call("network.endpoint.delete", params, value => endpointDeleteRpcResultSchema.parse(value)),
    endpointGet: (params: RpcParams<"network.endpoint.get">): Promise<RpcResult<"network.endpoint.get">> => rpcTransport.call("network.endpoint.get", params, value => endpointGetRpcResultSchema.parse(value)),
    endpointList: (params: RpcParams<"network.endpoint.list">): Promise<RpcResult<"network.endpoint.list">> => rpcTransport.call("network.endpoint.list", params, value => endpointListRpcResultSchema.parse(value)),
    endpointNextIdentity: (params: RpcParams<"network.endpoint.nextIdentity">): Promise<RpcResult<"network.endpoint.nextIdentity">> => rpcTransport.call("network.endpoint.nextIdentity", params, value => endpointNextIdentityRpcResultSchema.parse(value)),
    endpointStatus: (params: RpcParams<"network.endpoint.status">): Promise<RpcResult<"network.endpoint.status">> => rpcTransport.call("network.endpoint.status", params, value => endpointStatusRpcResultSchema.parse(value)),
    endpointUpdate: (params: RpcParams<"network.endpoint.update">): Promise<RpcResult<"network.endpoint.update">> => rpcTransport.call("network.endpoint.update", params, value => endpointUpdateRpcResultSchema.parse(value)),
    networkGet: (params: RpcParams<"network.get">): Promise<RpcResult<"network.get">> => rpcTransport.call("network.get", params, value => networkGetRpcResultSchema.parse(value)),
    networkList: (): Promise<RpcResult<"network.list">> => rpcTransport.call("network.list", empty, value => networkListRpcResultSchema.parse(value)),
    networkListPresets: (): Promise<RpcResult<"network.listPresets">> => rpcTransport.call("network.listPresets", empty, value => networkListPresetsRpcResultSchema.parse(value)),
    networkRpcStats: (params: RpcParams<"network.rpcStats">): Promise<RpcResult<"network.rpcStats">> => rpcTransport.call("network.rpcStats", params, value => networkRpcStatsRpcResultSchema.parse(value)),
    networkUpdate: (params: RpcParams<"network.update">): Promise<RpcResult<"network.update">> => rpcTransport.call("network.update", params, value => networkUpdateRpcResultSchema.parse(value)),
    quoterCreate: (params: RpcParams<"quoter.create">): Promise<RpcResult<"quoter.create">> => rpcTransport.call("quoter.create", params, value => quoterCreateRpcResultSchema.parse(value)),
    quoterDiscover: (params: RpcParams<"quoter.discover">): Promise<RpcResult<"quoter.discover">> => rpcTransport.call("quoter.discover", params, value => quoterDiscoverRpcResultSchema.parse(value)),
    quoterGet: (params: RpcParams<"quoter.get">): Promise<RpcResult<"quoter.get">> => rpcTransport.call("quoter.get", params, value => quoterGetRpcResultSchema.parse(value)),
    quoterList: (): Promise<RpcResult<"quoter.list">> => rpcTransport.call("quoter.list", empty, value => quoterListRpcResultSchema.parse(value)),
    quoterUpdate: (params: RpcParams<"quoter.update">): Promise<RpcResult<"quoter.update">> => rpcTransport.call("quoter.update", params, value => quoterUpdateRpcResultSchema.parse(value)),
    systemPing: (): Promise<RpcResult<"system.ping">> => rpcTransport.call("system.ping", empty, value => systemPingRpcResultSchema.parse(value)),
    transactionDecode: (params: RpcParams<"transaction.decode">): Promise<RpcResult<"transaction.decode">> => rpcTransport.call("transaction.decode", params, value => transactionDecodeRpcResultSchema.parse(value)),
    transactionSimulate: (params: RpcParams<"transaction.simulate">): Promise<RpcResult<"transaction.simulate">> => rpcTransport.call("transaction.simulate", params, value => transactionSimulateRpcResultSchema.parse(value)),
    vendorDisable: (params: RpcParams<"vendor.disable">): Promise<RpcResult<"vendor.disable">> => rpcTransport.call("vendor.disable", params, value => vendorDisableRpcResultSchema.parse(value)),
    vendorEnable: (params: RpcParams<"vendor.enable">): Promise<RpcResult<"vendor.enable">> => rpcTransport.call("vendor.enable", params, value => vendorEnableRpcResultSchema.parse(value)),
    vendorListAll: (): Promise<RpcResult<"vendor.listAll">> => rpcTransport.call("vendor.listAll", empty, value => vendorListAllRpcResultSchema.parse(value)),
    vendorListEnabled: (): Promise<RpcResult<"vendor.listEnabled">> => rpcTransport.call("vendor.listEnabled", empty, value => vendorListEnabledRpcResultSchema.parse(value)),
};
