/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AccAccountIndexRouteImport } from "./routes/acc/$account/index"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AccAccountIndexRoute = AccAccountIndexRouteImport.update({
  id: "/acc/$account/",
  path: "/acc/$account/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/acc/$account/": typeof AccAccountIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/acc/$account": typeof AccAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/acc/$account/": typeof AccAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/acc/$account/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/acc/$account"
  id: "__root__" | "/" | "/acc/$account/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccAccountIndexRoute: typeof AccAccountIndexRoute
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/$account/": {
      id: "/acc/$account/"
      path: "/acc/$account"
      fullPath: "/acc/$account/"
      preLoaderRoute: typeof AccAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccAccountIndexRoute: AccAccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
