/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteRouteImport } from "./routes/settings/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as SettingsNetworksRouteImport } from "./routes/settings/networks"
import { Route as AccAccountRouteRouteImport } from "./routes/acc/$account/route"
import { Route as AccAccountIndexRouteImport } from "./routes/acc/$account/index"
import { Route as AccAccountNewTxRouteImport } from "./routes/acc/$account/new-tx"
import { Route as AccAccountAssetsRouteImport } from "./routes/acc/$account/assets"

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsNetworksRoute = SettingsNetworksRouteImport.update({
  id: "/networks",
  path: "/networks",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AccAccountRouteRoute = AccAccountRouteRouteImport.update({
  id: "/acc/$account",
  path: "/acc/$account",
  getParentRoute: () => rootRouteImport,
} as any)
const AccAccountIndexRoute = AccAccountIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountNewTxRoute = AccAccountNewTxRouteImport.update({
  id: "/new-tx",
  path: "/new-tx",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountAssetsRoute = AccAccountAssetsRouteImport.update({
  id: "/assets",
  path: "/assets",
  getParentRoute: () => AccAccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/settings": typeof SettingsRouteRouteWithChildren
  "/acc/$account": typeof AccAccountRouteRouteWithChildren
  "/settings/networks": typeof SettingsNetworksRoute
  "/settings/": typeof SettingsIndexRoute
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/$account/": typeof AccAccountIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/settings/networks": typeof SettingsNetworksRoute
  "/settings": typeof SettingsIndexRoute
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/$account": typeof AccAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/settings": typeof SettingsRouteRouteWithChildren
  "/acc/$account": typeof AccAccountRouteRouteWithChildren
  "/settings/networks": typeof SettingsNetworksRoute
  "/settings/": typeof SettingsIndexRoute
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/$account/": typeof AccAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/settings"
    | "/acc/$account"
    | "/settings/networks"
    | "/settings/"
    | "/acc/$account/assets"
    | "/acc/$account/new-tx"
    | "/acc/$account/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/settings/networks"
    | "/settings"
    | "/acc/$account/assets"
    | "/acc/$account/new-tx"
    | "/acc/$account"
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/acc/$account"
    | "/settings/networks"
    | "/settings/"
    | "/acc/$account/assets"
    | "/acc/$account/new-tx"
    | "/acc/$account/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AccAccountRouteRoute: typeof AccAccountRouteRouteWithChildren
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/networks": {
      id: "/settings/networks"
      path: "/networks"
      fullPath: "/settings/networks"
      preLoaderRoute: typeof SettingsNetworksRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/acc/$account": {
      id: "/acc/$account"
      path: "/acc/$account"
      fullPath: "/acc/$account"
      preLoaderRoute: typeof AccAccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/$account/": {
      id: "/acc/$account/"
      path: "/"
      fullPath: "/acc/$account/"
      preLoaderRoute: typeof AccAccountIndexRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/new-tx": {
      id: "/acc/$account/new-tx"
      path: "/new-tx"
      fullPath: "/acc/$account/new-tx"
      preLoaderRoute: typeof AccAccountNewTxRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/assets": {
      id: "/acc/$account/assets"
      path: "/assets"
      fullPath: "/acc/$account/assets"
      preLoaderRoute: typeof AccAccountAssetsRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsNetworksRoute: typeof SettingsNetworksRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsNetworksRoute: SettingsNetworksRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AccAccountRouteRouteChildren {
  AccAccountAssetsRoute: typeof AccAccountAssetsRoute
  AccAccountNewTxRoute: typeof AccAccountNewTxRoute
  AccAccountIndexRoute: typeof AccAccountIndexRoute
}

const AccAccountRouteRouteChildren: AccAccountRouteRouteChildren = {
  AccAccountAssetsRoute: AccAccountAssetsRoute,
  AccAccountNewTxRoute: AccAccountNewTxRoute,
  AccAccountIndexRoute: AccAccountIndexRoute,
}

const AccAccountRouteRouteWithChildren = AccAccountRouteRoute._addFileChildren(
  AccAccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AccAccountRouteRoute: AccAccountRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
