/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteRouteImport } from "./routes/settings/route"
import { Route as OnboardingRouteRouteImport } from "./routes/onboarding/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as OnboardingIndexRouteImport } from "./routes/onboarding/index"
import { Route as SettingsNetworksRouteImport } from "./routes/settings/networks"
import { Route as OnboardingVendorsRouteImport } from "./routes/onboarding/vendors"
import { Route as OnboardingNetworksRouteImport } from "./routes/onboarding/networks"
import { Route as OnboardingAccountsRouteImport } from "./routes/onboarding/accounts"
import { Route as AccAccountRouteRouteImport } from "./routes/acc/$account/route"
import { Route as AccNewIndexRouteImport } from "./routes/acc/new/index"
import { Route as AccAccountIndexRouteImport } from "./routes/acc/$account/index"
import { Route as AccNewKeyRouteImport } from "./routes/acc/new/key"
import { Route as AccImportViewRouteImport } from "./routes/acc/import/view"
import { Route as AccImportSafeRouteImport } from "./routes/acc/import/safe"
import { Route as AccImportKeyRouteImport } from "./routes/acc/import/key"
import { Route as AccAccountNewTxRouteImport } from "./routes/acc/$account/new-tx"
import { Route as AccAccountAssetsRouteImport } from "./routes/acc/$account/assets"
import { Route as AccAccountSettingsRouteRouteImport } from "./routes/acc/$account/settings/route"
import { Route as AccAccountSettingsIndexRouteImport } from "./routes/acc/$account/settings/index"
import { Route as AccAccountSettingsTokensRouteImport } from "./routes/acc/$account/settings/tokens"
import { Route as AccAccountSettingsDangerRouteImport } from "./routes/acc/$account/settings/danger"

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const SettingsNetworksRoute = SettingsNetworksRouteImport.update({
  id: "/networks",
  path: "/networks",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const OnboardingVendorsRoute = OnboardingVendorsRouteImport.update({
  id: "/vendors",
  path: "/vendors",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingNetworksRoute = OnboardingNetworksRouteImport.update({
  id: "/networks",
  path: "/networks",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAccountsRoute = OnboardingAccountsRouteImport.update({
  id: "/accounts",
  path: "/accounts",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AccAccountRouteRoute = AccAccountRouteRouteImport.update({
  id: "/acc/$account",
  path: "/acc/$account",
  getParentRoute: () => rootRouteImport,
} as any)
const AccNewIndexRoute = AccNewIndexRouteImport.update({
  id: "/acc/new/",
  path: "/acc/new/",
  getParentRoute: () => rootRouteImport,
} as any)
const AccAccountIndexRoute = AccAccountIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccNewKeyRoute = AccNewKeyRouteImport.update({
  id: "/acc/new/key",
  path: "/acc/new/key",
  getParentRoute: () => rootRouteImport,
} as any)
const AccImportViewRoute = AccImportViewRouteImport.update({
  id: "/acc/import/view",
  path: "/acc/import/view",
  getParentRoute: () => rootRouteImport,
} as any)
const AccImportSafeRoute = AccImportSafeRouteImport.update({
  id: "/acc/import/safe",
  path: "/acc/import/safe",
  getParentRoute: () => rootRouteImport,
} as any)
const AccImportKeyRoute = AccImportKeyRouteImport.update({
  id: "/acc/import/key",
  path: "/acc/import/key",
  getParentRoute: () => rootRouteImport,
} as any)
const AccAccountNewTxRoute = AccAccountNewTxRouteImport.update({
  id: "/new-tx",
  path: "/new-tx",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountAssetsRoute = AccAccountAssetsRouteImport.update({
  id: "/assets",
  path: "/assets",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountSettingsRouteRoute = AccAccountSettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AccAccountRouteRoute,
} as any)
const AccAccountSettingsIndexRoute = AccAccountSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AccAccountSettingsRouteRoute,
} as any)
const AccAccountSettingsTokensRoute =
  AccAccountSettingsTokensRouteImport.update({
    id: "/tokens",
    path: "/tokens",
    getParentRoute: () => AccAccountSettingsRouteRoute,
  } as any)
const AccAccountSettingsDangerRoute =
  AccAccountSettingsDangerRouteImport.update({
    id: "/danger",
    path: "/danger",
    getParentRoute: () => AccAccountSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRouteRouteWithChildren
  "/settings": typeof SettingsRouteRouteWithChildren
  "/acc/$account": typeof AccAccountRouteRouteWithChildren
  "/onboarding/accounts": typeof OnboardingAccountsRoute
  "/onboarding/networks": typeof OnboardingNetworksRoute
  "/onboarding/vendors": typeof OnboardingVendorsRoute
  "/settings/networks": typeof SettingsNetworksRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/acc/$account/settings": typeof AccAccountSettingsRouteRouteWithChildren
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/import/key": typeof AccImportKeyRoute
  "/acc/import/safe": typeof AccImportSafeRoute
  "/acc/import/view": typeof AccImportViewRoute
  "/acc/new/key": typeof AccNewKeyRoute
  "/acc/$account/": typeof AccAccountIndexRoute
  "/acc/new/": typeof AccNewIndexRoute
  "/acc/$account/settings/danger": typeof AccAccountSettingsDangerRoute
  "/acc/$account/settings/tokens": typeof AccAccountSettingsTokensRoute
  "/acc/$account/settings/": typeof AccAccountSettingsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/onboarding/accounts": typeof OnboardingAccountsRoute
  "/onboarding/networks": typeof OnboardingNetworksRoute
  "/onboarding/vendors": typeof OnboardingVendorsRoute
  "/settings/networks": typeof SettingsNetworksRoute
  "/onboarding": typeof OnboardingIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/import/key": typeof AccImportKeyRoute
  "/acc/import/safe": typeof AccImportSafeRoute
  "/acc/import/view": typeof AccImportViewRoute
  "/acc/new/key": typeof AccNewKeyRoute
  "/acc/$account": typeof AccAccountIndexRoute
  "/acc/new": typeof AccNewIndexRoute
  "/acc/$account/settings/danger": typeof AccAccountSettingsDangerRoute
  "/acc/$account/settings/tokens": typeof AccAccountSettingsTokensRoute
  "/acc/$account/settings": typeof AccAccountSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRouteRouteWithChildren
  "/settings": typeof SettingsRouteRouteWithChildren
  "/acc/$account": typeof AccAccountRouteRouteWithChildren
  "/onboarding/accounts": typeof OnboardingAccountsRoute
  "/onboarding/networks": typeof OnboardingNetworksRoute
  "/onboarding/vendors": typeof OnboardingVendorsRoute
  "/settings/networks": typeof SettingsNetworksRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/acc/$account/settings": typeof AccAccountSettingsRouteRouteWithChildren
  "/acc/$account/assets": typeof AccAccountAssetsRoute
  "/acc/$account/new-tx": typeof AccAccountNewTxRoute
  "/acc/import/key": typeof AccImportKeyRoute
  "/acc/import/safe": typeof AccImportSafeRoute
  "/acc/import/view": typeof AccImportViewRoute
  "/acc/new/key": typeof AccNewKeyRoute
  "/acc/$account/": typeof AccAccountIndexRoute
  "/acc/new/": typeof AccNewIndexRoute
  "/acc/$account/settings/danger": typeof AccAccountSettingsDangerRoute
  "/acc/$account/settings/tokens": typeof AccAccountSettingsTokensRoute
  "/acc/$account/settings/": typeof AccAccountSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/onboarding"
    | "/settings"
    | "/acc/$account"
    | "/onboarding/accounts"
    | "/onboarding/networks"
    | "/onboarding/vendors"
    | "/settings/networks"
    | "/onboarding/"
    | "/settings/"
    | "/acc/$account/settings"
    | "/acc/$account/assets"
    | "/acc/$account/new-tx"
    | "/acc/import/key"
    | "/acc/import/safe"
    | "/acc/import/view"
    | "/acc/new/key"
    | "/acc/$account/"
    | "/acc/new/"
    | "/acc/$account/settings/danger"
    | "/acc/$account/settings/tokens"
    | "/acc/$account/settings/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/onboarding/accounts"
    | "/onboarding/networks"
    | "/onboarding/vendors"
    | "/settings/networks"
    | "/onboarding"
    | "/settings"
    | "/acc/$account/assets"
    | "/acc/$account/new-tx"
    | "/acc/import/key"
    | "/acc/import/safe"
    | "/acc/import/view"
    | "/acc/new/key"
    | "/acc/$account"
    | "/acc/new"
    | "/acc/$account/settings/danger"
    | "/acc/$account/settings/tokens"
    | "/acc/$account/settings"
  id:
    | "__root__"
    | "/"
    | "/onboarding"
    | "/settings"
    | "/acc/$account"
    | "/onboarding/accounts"
    | "/onboarding/networks"
    | "/onboarding/vendors"
    | "/settings/networks"
    | "/onboarding/"
    | "/settings/"
    | "/acc/$account/settings"
    | "/acc/$account/assets"
    | "/acc/$account/new-tx"
    | "/acc/import/key"
    | "/acc/import/safe"
    | "/acc/import/view"
    | "/acc/new/key"
    | "/acc/$account/"
    | "/acc/new/"
    | "/acc/$account/settings/danger"
    | "/acc/$account/settings/tokens"
    | "/acc/$account/settings/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AccAccountRouteRoute: typeof AccAccountRouteRouteWithChildren
  AccImportKeyRoute: typeof AccImportKeyRoute
  AccImportSafeRoute: typeof AccImportSafeRoute
  AccImportViewRoute: typeof AccImportViewRoute
  AccNewKeyRoute: typeof AccNewKeyRoute
  AccNewIndexRoute: typeof AccNewIndexRoute
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/onboarding/": {
      id: "/onboarding/"
      path: "/"
      fullPath: "/onboarding/"
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/settings/networks": {
      id: "/settings/networks"
      path: "/networks"
      fullPath: "/settings/networks"
      preLoaderRoute: typeof SettingsNetworksRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/onboarding/vendors": {
      id: "/onboarding/vendors"
      path: "/vendors"
      fullPath: "/onboarding/vendors"
      preLoaderRoute: typeof OnboardingVendorsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/onboarding/networks": {
      id: "/onboarding/networks"
      path: "/networks"
      fullPath: "/onboarding/networks"
      preLoaderRoute: typeof OnboardingNetworksRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/onboarding/accounts": {
      id: "/onboarding/accounts"
      path: "/accounts"
      fullPath: "/onboarding/accounts"
      preLoaderRoute: typeof OnboardingAccountsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/acc/$account": {
      id: "/acc/$account"
      path: "/acc/$account"
      fullPath: "/acc/$account"
      preLoaderRoute: typeof AccAccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/new/": {
      id: "/acc/new/"
      path: "/acc/new"
      fullPath: "/acc/new/"
      preLoaderRoute: typeof AccNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/$account/": {
      id: "/acc/$account/"
      path: "/"
      fullPath: "/acc/$account/"
      preLoaderRoute: typeof AccAccountIndexRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/new/key": {
      id: "/acc/new/key"
      path: "/acc/new/key"
      fullPath: "/acc/new/key"
      preLoaderRoute: typeof AccNewKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/import/view": {
      id: "/acc/import/view"
      path: "/acc/import/view"
      fullPath: "/acc/import/view"
      preLoaderRoute: typeof AccImportViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/import/safe": {
      id: "/acc/import/safe"
      path: "/acc/import/safe"
      fullPath: "/acc/import/safe"
      preLoaderRoute: typeof AccImportSafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/import/key": {
      id: "/acc/import/key"
      path: "/acc/import/key"
      fullPath: "/acc/import/key"
      preLoaderRoute: typeof AccImportKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/acc/$account/new-tx": {
      id: "/acc/$account/new-tx"
      path: "/new-tx"
      fullPath: "/acc/$account/new-tx"
      preLoaderRoute: typeof AccAccountNewTxRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/assets": {
      id: "/acc/$account/assets"
      path: "/assets"
      fullPath: "/acc/$account/assets"
      preLoaderRoute: typeof AccAccountAssetsRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/settings": {
      id: "/acc/$account/settings"
      path: "/settings"
      fullPath: "/acc/$account/settings"
      preLoaderRoute: typeof AccAccountSettingsRouteRouteImport
      parentRoute: typeof AccAccountRouteRoute
    }
    "/acc/$account/settings/": {
      id: "/acc/$account/settings/"
      path: "/"
      fullPath: "/acc/$account/settings/"
      preLoaderRoute: typeof AccAccountSettingsIndexRouteImport
      parentRoute: typeof AccAccountSettingsRouteRoute
    }
    "/acc/$account/settings/tokens": {
      id: "/acc/$account/settings/tokens"
      path: "/tokens"
      fullPath: "/acc/$account/settings/tokens"
      preLoaderRoute: typeof AccAccountSettingsTokensRouteImport
      parentRoute: typeof AccAccountSettingsRouteRoute
    }
    "/acc/$account/settings/danger": {
      id: "/acc/$account/settings/danger"
      path: "/danger"
      fullPath: "/acc/$account/settings/danger"
      preLoaderRoute: typeof AccAccountSettingsDangerRouteImport
      parentRoute: typeof AccAccountSettingsRouteRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingAccountsRoute: typeof OnboardingAccountsRoute
  OnboardingNetworksRoute: typeof OnboardingNetworksRoute
  OnboardingVendorsRoute: typeof OnboardingVendorsRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAccountsRoute: OnboardingAccountsRoute,
  OnboardingNetworksRoute: OnboardingNetworksRoute,
  OnboardingVendorsRoute: OnboardingVendorsRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsNetworksRoute: typeof SettingsNetworksRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsNetworksRoute: SettingsNetworksRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AccAccountSettingsRouteRouteChildren {
  AccAccountSettingsDangerRoute: typeof AccAccountSettingsDangerRoute
  AccAccountSettingsTokensRoute: typeof AccAccountSettingsTokensRoute
  AccAccountSettingsIndexRoute: typeof AccAccountSettingsIndexRoute
}

const AccAccountSettingsRouteRouteChildren: AccAccountSettingsRouteRouteChildren =
  {
    AccAccountSettingsDangerRoute: AccAccountSettingsDangerRoute,
    AccAccountSettingsTokensRoute: AccAccountSettingsTokensRoute,
    AccAccountSettingsIndexRoute: AccAccountSettingsIndexRoute,
  }

const AccAccountSettingsRouteRouteWithChildren =
  AccAccountSettingsRouteRoute._addFileChildren(
    AccAccountSettingsRouteRouteChildren,
  )

interface AccAccountRouteRouteChildren {
  AccAccountSettingsRouteRoute: typeof AccAccountSettingsRouteRouteWithChildren
  AccAccountAssetsRoute: typeof AccAccountAssetsRoute
  AccAccountNewTxRoute: typeof AccAccountNewTxRoute
  AccAccountIndexRoute: typeof AccAccountIndexRoute
}

const AccAccountRouteRouteChildren: AccAccountRouteRouteChildren = {
  AccAccountSettingsRouteRoute: AccAccountSettingsRouteRouteWithChildren,
  AccAccountAssetsRoute: AccAccountAssetsRoute,
  AccAccountNewTxRoute: AccAccountNewTxRoute,
  AccAccountIndexRoute: AccAccountIndexRoute,
}

const AccAccountRouteRouteWithChildren = AccAccountRouteRoute._addFileChildren(
  AccAccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AccAccountRouteRoute: AccAccountRouteRouteWithChildren,
  AccImportKeyRoute: AccImportKeyRoute,
  AccImportSafeRoute: AccImportSafeRoute,
  AccImportViewRoute: AccImportViewRoute,
  AccNewKeyRoute: AccNewKeyRoute,
  AccNewIndexRoute: AccNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
