/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/acc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all accounts
         * @description GET /api/acc
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an account
         * @description POST /api/acc
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Account"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Account"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an account by ID
         * @description GET /api/acc/:account_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Account"];
                    };
                };
            };
        };
        /**
         * Update an account by ID
         * @description PUT /api/acc/:account_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AccountUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Account"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete an account by ID
         * @description DELETE /api/acc/:account_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/next-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next account ID
         * @description GET /api/acc/next-id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the assets of an account
         * @description GET /api/acc/:account_identity/assets
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/asset/{asset_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add an asset to an account
         * @description POST /api/acc/:account_identity/asset/:asset_identity
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        /**
         * Remove an asset from an account
         * @description DELETE /api/acc/:account_identity/asset/:asset_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/asset/{asset_identity}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the balance of a single asset for an account
         * @description GET /api/acc/:account_identity/asset/:asset_identity/balance
         */
        get: {
            parameters: {
                query: {
                    display_currency: string;
                };
                header?: never;
                path: {
                    account_identity: number;
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountBalance"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the balances of an account
         * @description GET /api/acc/:account_identity/balances
         */
        get: {
            parameters: {
                query: {
                    display_currency: string;
                    fresh?: boolean;
                };
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountBalances"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account layout (groups + ordered accounts)
         * @description GET /api/acc/layout
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountLayout"];
                    };
                };
            };
        };
        /**
         * Update account layout (bulk reorder + group membership)
         * @description PUT /api/acc/layout
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AccountLayoutUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountLayout"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account group
         * @description POST /api/acc/groups
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AccountGroupCreate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountGroup"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/groups/{group_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update an account group
         * @description PUT /api/acc/groups/:group_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    group_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AccountGroupUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountGroup"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete an account group
         * @description DELETE /api/acc/groups/:group_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    group_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/tx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all transactions for an account
         * @description GET /api/acc/:account_identity/tx
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountTxResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/{account_identity}/tx/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all pending transactions for an account
         * @description GET /api/acc/:account_identity/tx/pending
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AccountTxResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/generate/mnemonic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate a new BIP-39 mnemonic
         * @description GET /api/acc/generate/mnemonic
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["GenerateMnemonicResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/derive/default-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the default BIP-44 Ethereum derivation path
         * @description GET /api/acc/derive/default-path
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DefaultDerivationPathResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/derive/mnemonic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Derive addresses from a mnemonic and derivation paths
         * @description POST /api/acc/derive/mnemonic
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["DeriveMnemonicRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DeriveMnemonicResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acc/derive/private-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Derive an address from a private key
         * @description POST /api/acc/derive/private-key
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["DerivePrivateKeyRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DeriveAddressResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all networks
         * @description GET /api/net
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworksResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a network
         * @description POST /api/net
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Network"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get network presets
         * @description GET /api/net/presets
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network by ID
         * @description GET /api/net/:network_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        /**
         * Update a network by ID
         * @description PUT /api/net/:network_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Network"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a network by ID
         * @description DELETE /api/net/:network_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/rpc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cached RPC pool stats for a network
         * @description GET /api/net/:network_identity/rpc
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RpcPoolStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover metadata for a network
         * @description GET /api/net/:network_identity/metadata
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkMetadataDiscovery"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get network endpoints
         * @description GET /api/net/:network_identity/endpoints
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a network endpoint
         * @description POST /api/net/:network_identity/endpoints
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/endpoints/next-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next network endpoint ID
         * @description GET /api/net/:network_identity/endpoints/next-id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/endpoints/{endpoint_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network endpoint by ID
         * @description GET /api/net/:network_identity/endpoints/:endpoint_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                    endpoint_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        /**
         * Update a network endpoint by ID
         * @description PUT /api/net/:network_identity/endpoints/:endpoint_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                    endpoint_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NetworkEndpointUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["NetworkEndpoint"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a network endpoint by ID
         * @description DELETE /api/net/:network_identity/endpoints/:endpoint_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                    endpoint_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/endpoints/{endpoint_identity}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a network endpoint status
         * @description GET /api/net/:network_identity/endpoints/:endpoint_identity/status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                    endpoint_identity: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RpcStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate a transaction
         * @description POST /api/net/:network_identity/simulate
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["SimulateTransactionRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SimulateTransactionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net/{network_identity}/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decode a transaction
         * @description POST /api/net/:network_identity/decode
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    network_identity: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["DecodeTransactionRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DecodeTransactionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all assets
         * @description GET /api/asset
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AssetsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an asset
         * @description POST /api/asset
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["Asset"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Asset"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/{asset_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an asset by ID
         * @description GET /api/asset/:asset_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Asset"];
                    };
                };
            };
        };
        /**
         * Update an asset by ID
         * @description PUT /api/asset/:asset_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AssetUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Asset"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete an asset by ID
         * @description DELETE /api/asset/:asset_identity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/{asset_identity}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover metadata for an asset
         * @description GET /api/asset/:asset_identity/metadata
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AssetMetadataDiscovery"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/{asset_identity}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quote an asset
         * @description GET /api/asset/:asset_identity/quote
         */
        get: {
            parameters: {
                query?: {
                    display_asset?: string;
                };
                header?: never;
                path: {
                    asset_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quoter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all quoters
         * @description GET /api/quoter
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["QuotersResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a quoter
         * @description POST /api/quoter
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["QuoterCreate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Quoter"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quoter/{quoter_identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a quoter by id
         * @description GET /api/quoter/:quoter_identity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    quoter_identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Quoter"];
                    };
                };
            };
        };
        /**
         * Update a quoter
         * @description PUT /api/quoter/:quoter_identity
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    quoter_identity: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["QuoterUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Quoter"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quoter/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Quoter
         * @description POST /api/quoter/discover
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["QuoterDiscovery"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["QuoterDiscoveryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enabled vendors
         * @description GET /api/vendor
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["VendorsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all vendors
         * @description GET /api/vendor/all
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["VendorFlagInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/{flag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a vendor flag
         * @description POST /api/vendor/:flag
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    flag: components["schemas"]["VendorFlag"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        /**
         * Disable a vendor flag
         * @description POST /api/vendor/:flag
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    flag: components["schemas"]["VendorFlag"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all OpenLV connections
         * @description GET /api/connections
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ConnectionsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an OpenLV connection
         * @description POST /api/connections
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ConnectConnectionRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["FrontendConnection"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect an OpenLV connection
         * @description POST /api/connections/:connection_id/disconnect
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["FrontendConnection"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an OpenLV connection
         * @description DELETE /api/connections/:connection_id
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": Record<string, never>;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all vendor flags
         * @description GET /api/health
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** Account */
        Account: {
            /** Format: uint64 */
            account_identity: number;
            name: string;
            networks: number[];
            metadata: components["schemas"]["WalletType"];
            /** Format: uint64 */
            group_id?: number;
            /** Format: uint32 */
            display_order: number;
        };
        /** AccountBalance */
        AccountBalance: {
            asset_identity: string;
            balance?: string;
            balance_error?: string;
            asset_quote?: string;
            asset_quote_error?: string;
            asset_24h_quote?: string;
            asset_24h_quote_error?: string;
            balance_quote?: string;
            balance_quote_error?: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** AccountBalances */
        AccountBalances: {
            balances: components["schemas"]["AccountBalance"][];
            total_quote?: string;
            /** Format: date-time */
            updated_at: string;
            asset: string;
            errors: string[];
        };
        /** AccountGroup */
        AccountGroup: {
            /** Format: uint64 */
            group_identity: number;
            name: string;
            /** Format: uint32 */
            display_order: number;
        };
        /** AccountGroupCreate */
        AccountGroupCreate: {
            name: string;
        };
        /** AccountGroupUpdate */
        AccountGroupUpdate: {
            name?: string;
        };
        /** AccountLayout */
        AccountLayout: {
            groups: components["schemas"]["AccountGroup"][];
            accounts: components["schemas"]["Account"][];
        };
        /** AccountLayoutAccountEntry */
        AccountLayoutAccountEntry: {
            /** Format: uint64 */
            account_identity: number;
            /** Format: uint64 */
            group_id?: number;
            /** Format: uint32 */
            display_order: number;
        };
        /** AccountLayoutGroupEntry */
        AccountLayoutGroupEntry: {
            /** Format: uint64 */
            group_identity: number;
            name: string;
            /** Format: uint32 */
            display_order: number;
        };
        /** AccountLayoutUpdate */
        AccountLayoutUpdate: {
            groups: components["schemas"]["AccountLayoutGroupEntry"][];
            accounts: components["schemas"]["AccountLayoutAccountEntry"][];
        };
        /** AccountTxResponse */
        AccountTxResponse: {
            transactions: components["schemas"]["Tx"][];
        };
        /** AccountUpdate */
        AccountUpdate: {
            name?: string;
            networks?: number[];
            metadata?: components["schemas"]["WalletType"];
        };
        /** AccountsResponse */
        AccountsResponse: {
            accounts: components["schemas"]["Account"][];
        };
        /** Asset */
        Asset: {
            asset_identity: string;
            asset_name: string;
            asset_symbol: string;
            /** Format: uint8 */
            asset_decimals: number;
            asset_icon_url?: string;
        };
        /** AssetMetadataDiscovery */
        AssetMetadataDiscovery: {
            asset_identity: string;
            options: {
                [key: string]: components["schemas"]["AssetMetadataOption"];
            };
        };
        /** AssetMetadataOption */
        AssetMetadataOption: {
            name?: string;
            symbol?: string;
            /** Format: uint8 */
            decimals?: number;
            icon_url?: string;
        };
        /** AssetUpdate */
        AssetUpdate: {
            asset_name?: string;
            asset_symbol?: string;
            /** Format: uint8 */
            asset_decimals?: number;
            asset_icon_url?: string;
        };
        /** AssetsResponse */
        AssetsResponse: {
            assets: components["schemas"]["Asset"][];
        };
        /** ConnectConnectionRequest */
        ConnectConnectionRequest: {
            url: string;
            /** Format: uint64 */
            account_identity: number;
            /** Format: uint64 */
            network_identity: number;
        };
        /** @enum {string} */
        ConnectionStatus: "created" | "signaling" | "ready" | "linking" | "connected" | "disconnected";
        /** ConnectionsResponse */
        ConnectionsResponse: {
            connections: components["schemas"]["FrontendConnection"][];
        };
        /** DecodeTransactionRequest */
        DecodeTransactionRequest: {
            /** Format: address */
            from?: string;
            /** Format: address */
            to: string;
            /** Format: uint256 */
            value?: string;
            /** Format: bytes */
            data?: string;
        };
        /** DecodeTransactionResponse */
        DecodeTransactionResponse: {
            call: components["schemas"]["DecodedCall"];
        };
        /** @description Best-effort decode result. */
        Decoded: components["schemas"]["Decoded_Verified"] | components["schemas"]["Decoded_SignatureFallback"] | components["schemas"]["Decoded_Raw"];
        /**
         * DecodedCall
         * @description High-level decoded call output.
         */
        DecodedCall: {
            /** Format: address */
            from?: string;
            /** Format: address */
            to: string;
            /** Format: uint256 */
            value: string;
            operation?: string;
            /** Format: bytes */
            data: string;
            /** Format: bytes */
            selector?: string;
            decoded: components["schemas"]["Decoded"];
            subcalls: components["schemas"]["DecodedCall"][];
        };
        /**
         * DecodedContract
         * @description Contract provenance used during decoding.
         */
        DecodedContract: {
            /** Format: address */
            address: string;
            verified_name?: string;
            proxy?: components["schemas"]["DecodedProxy"];
        };
        /**
         * DecodedFunction
         * @description ABI-decoded function call.
         */
        DecodedFunction: {
            contract: components["schemas"]["DecodedContract"];
            /** Format: bytes */
            selector: string;
            function: string;
            signature: string;
            params: components["schemas"]["DecodedParam"][];
        };
        /**
         * DecodedParam
         * @description One decoded input parameter.
         */
        DecodedParam: {
            name?: string;
            ty: string;
            value: unknown;
        };
        /**
         * DecodedProxy
         * @description Proxy metadata when decoding through a verified implementation.
         */
        DecodedProxy: {
            proxy_type?: string;
            /** Format: address */
            implementation: string;
            implementation_name?: string;
        };
        /** @description Best-effort decode result. */
        Decoded_Raw: {
            /**
             * @example raw
             * @enum {string}
             */
            kind: "raw";
        } & components["schemas"]["RawCall"];
        /** @description Best-effort decode result. */
        Decoded_SignatureFallback: {
            /**
             * @example signature_fallback
             * @enum {string}
             */
            kind: "signature_fallback";
        } & components["schemas"]["SignatureFallback"];
        /** @description Best-effort decode result. */
        Decoded_Verified: {
            /**
             * @example verified
             * @enum {string}
             */
            kind: "verified";
        } & components["schemas"]["DecodedFunction"];
        /** DefaultDerivationPathResponse */
        DefaultDerivationPathResponse: {
            path: string;
        };
        /** DeriveAddressResponse */
        DeriveAddressResponse: {
            address: string;
        };
        /** DeriveMnemonicRequest */
        DeriveMnemonicRequest: {
            mnemonic: string;
            paths: string[];
        };
        /** DeriveMnemonicResponse */
        DeriveMnemonicResponse: {
            results: components["schemas"]["DeriveMnemonicResult"][];
        };
        /** DeriveMnemonicResult */
        DeriveMnemonicResult: {
            path: string;
            address: string;
        };
        /** DerivePrivateKeyRequest */
        DerivePrivateKeyRequest: {
            private_key: string;
        };
        /** EOAWallet */
        EOAWallet: {
            /** Format: address */
            evm_address: string;
        };
        /** Erc4626QuoterConfig */
        Erc4626QuoterConfig: Record<string, never>;
        /** FixedQuoterConfig */
        FixedQuoterConfig: {
            price: string;
            /** Format: uint8 */
            decimals: number;
            /** Format: uint8 */
            token_in_decimals: number;
            /** Format: uint8 */
            token_out_decimals: number;
        };
        /** FrontendConnection */
        FrontendConnection: {
            /** Format: uuid */
            connection_id: string;
            status: components["schemas"]["ConnectionStatus"];
            /** Format: uint64 */
            account_identity: number;
            /** Format: uint64 */
            network_identity: number;
        };
        /** GenerateMnemonicResponse */
        GenerateMnemonicResponse: {
            mnemonic: string;
        };
        /** Network */
        Network: {
            /**
             * Format: uint64
             * @description evm chain id
             */
            network_identity: number;
            /** @description name, Ethereum Mainnet, Optimism, etc */
            network_name: string;
            /** @description icon url, https://example.com/icon.png, etc */
            network_icon_url?: string;
        };
        /** NetworkEndpoint */
        NetworkEndpoint: {
            /** Format: int32 */
            endpoint_identity: number;
            endpoint_label?: string;
            endpoint_type: string;
            endpoint_url: string;
            endpoint_disabled: boolean;
            /** Format: uint64 */
            network_identity: number;
        };
        /** NetworkEndpointUpdate */
        NetworkEndpointUpdate: {
            endpoint_label?: string;
            endpoint_type?: string;
            endpoint_url?: string;
            endpoint_disabled?: boolean;
        };
        /** NetworkMetadataDiscovery */
        NetworkMetadataDiscovery: {
            /** Format: uint64 */
            network_identity: number;
            options: {
                [key: string]: components["schemas"]["NetworkMetadataOption"];
            };
        };
        /** NetworkMetadataOption */
        NetworkMetadataOption: {
            icon_url?: string;
        };
        /** NetworkUpdate */
        NetworkUpdate: {
            network_name?: string;
            network_icon_url?: string;
        };
        /** NetworksResponse */
        NetworksResponse: {
            networks: components["schemas"]["Network"][];
        };
        /** Quoter */
        Quoter: {
            quoter_identity: string;
            quoter_name: string;
            token_a: string;
            token_b: string;
            config: components["schemas"]["QuoterConfig"];
            enabled: boolean;
            watch: boolean;
        };
        QuoterConfig: components["schemas"]["QuoterConfig_Fixed"] | components["schemas"]["QuoterConfig_Erc4626"] | components["schemas"]["QuoterConfig_UniswapV2"] | components["schemas"]["QuoterConfig_UniswapV3"];
        QuoterConfig_Erc4626: {
            /**
             * @example erc4626
             * @enum {string}
             */
            type: "erc4626";
        } & components["schemas"]["Erc4626QuoterConfig"];
        QuoterConfig_Fixed: {
            /**
             * @example fixed
             * @enum {string}
             */
            type: "fixed";
        } & components["schemas"]["FixedQuoterConfig"];
        QuoterConfig_UniswapV2: {
            /**
             * @example uniswap_v2
             * @enum {string}
             */
            type: "uniswap_v2";
        } & components["schemas"]["UniswapV2QuoterConfig"];
        QuoterConfig_UniswapV3: {
            /**
             * @example uniswap_v3
             * @enum {string}
             */
            type: "uniswap_v3";
        } & components["schemas"]["UniswapV3QuoterConfig"];
        /** QuoterCreate */
        QuoterCreate: {
            quoter_name: string;
            token_a: string;
            token_b: string;
            config: components["schemas"]["QuoterConfig"];
            enabled: boolean;
            watch: boolean;
        };
        /** QuoterDiscovery */
        QuoterDiscovery: {
            token_a: string;
            token_b?: string;
        };
        /** QuoterDiscoveryResponse */
        QuoterDiscoveryResponse: {
            erc4626?: string;
            uniswap_v2?: components["schemas"]["UniswapV2Pair"];
            uniswap_v3?: components["schemas"]["UniswapV3Pool"][];
        };
        /** QuoterUpdate */
        QuoterUpdate: {
            quoter_name?: string;
            token_a?: string;
            token_b?: string;
            config?: components["schemas"]["QuoterConfig"];
            enabled?: boolean;
            watch?: boolean;
        };
        /** QuotersResponse */
        QuotersResponse: {
            quoters: components["schemas"]["Quoter"][];
        };
        /** RailgunWallet */
        RailgunWallet: {
            railgun_address: string;
        };
        /**
         * RawCall
         * @description Fallback when nothing better can be decoded.
         */
        RawCall: {
            /** Format: bytes */
            data: string;
        };
        /** RpcCallSample */
        RpcCallSample: {
            /** Format: uint64 */
            timestamp: number;
            methods: string[];
            /** Format: uint64 */
            request_count: number;
            /** Format: uint64 */
            duration_ms: number;
            success: boolean;
            error?: string;
        };
        /** RpcEndpointStats */
        RpcEndpointStats: {
            /** Format: uint64 */
            in_flight: number;
            /** Format: uint64 */
            queued: number;
            /** Format: uint64 */
            max_in_flight: number;
            /** Format: uint64 */
            total_requests: number;
            /** Format: uint64 */
            total_errors: number;
            /** Format: uint64 */
            total_rate_limited: number;
            /** Format: uint64 */
            average_duration_ms: number;
            /** Format: uint64 */
            connection_attempts: number;
            /** Format: uint64 */
            connection_successes: number;
            /** Format: uint64 */
            connection_failures: number;
            /** Format: uint64 */
            last_request_at?: number;
            /** Format: uint64 */
            last_error_at?: number;
            /** Format: uint64 */
            last_connected_at?: number;
            last_error?: string;
            methods: components["schemas"]["RpcMethodStats"][];
            recent: components["schemas"]["RpcCallSample"][];
        };
        /** RpcMethodStats */
        RpcMethodStats: {
            method: string;
            /** Format: uint64 */
            total: number;
            /** Format: uint64 */
            errors: number;
        };
        /** RpcPoolEndpointStats */
        RpcPoolEndpointStats: {
            /** Format: int32 */
            endpoint_identity: number;
            status: string;
            /** Format: uint64 */
            in_flight: number;
            /** Format: uint64 */
            queued: number;
            /** Format: uint64 */
            total_requests: number;
            /** Format: uint64 */
            total_errors: number;
        };
        /** RpcPoolStats */
        RpcPoolStats: {
            /** Format: uint64 */
            network_identity: number;
            /** Format: uint64 */
            endpoint_count: number;
            /** Format: uint64 */
            alive_count: number;
            /** Format: uint64 */
            dead_count: number;
            /** Format: uint64 */
            disabled_count: number;
            /** Format: uint64 */
            in_flight: number;
            /** Format: uint64 */
            queued: number;
            /** Format: uint64 */
            total_requests: number;
            /** Format: uint64 */
            total_errors: number;
            endpoints: components["schemas"]["RpcPoolEndpointStats"][];
        };
        RpcStatus: components["schemas"]["RpcStatus_Alive"] | components["schemas"]["RpcStatus_Dead"] | components["schemas"]["RpcStatus_Disabled"];
        /** RpcStatusAlive */
        RpcStatusAlive: {
            /** Format: uint64 */
            block_number: number;
            /** Format: uint64 */
            network_identity: number;
            /** Format: uint64 */
            timestamp: number;
            rpc: components["schemas"]["RpcEndpointStats"];
        };
        /** RpcStatusDead */
        RpcStatusDead: {
            error: string;
            rpc: components["schemas"]["RpcEndpointStats"];
        };
        /** RpcStatusDisabled */
        RpcStatusDisabled: {
            rpc: components["schemas"]["RpcEndpointStats"];
        };
        RpcStatus_Alive: {
            /**
             * @example Alive
             * @enum {string}
             */
            status: "Alive";
        } & components["schemas"]["RpcStatusAlive"];
        RpcStatus_Dead: {
            /**
             * @example Dead
             * @enum {string}
             */
            status: "Dead";
        } & components["schemas"]["RpcStatusDead"];
        RpcStatus_Disabled: {
            /**
             * @example Disabled
             * @enum {string}
             */
            status: "Disabled";
        } & components["schemas"]["RpcStatusDisabled"];
        /** SafeWallet */
        SafeWallet: {
            /** Format: address */
            evm_address: string;
        };
        /** SafeWalletTxExtra */
        SafeWalletTxExtra: {
            /** Format: uint64 */
            nonce?: number;
            execution_date?: string;
            /** Format: bytes */
            safe_tx_hash?: string;
            /** Format: address */
            proposer?: string;
            /** Format: address */
            executor?: string;
            is_successful?: boolean;
            is_executed?: boolean;
            origin?: string;
            extra: unknown;
        };
        /**
         * SignatureFallback
         * @description Fallback when only 4byte resolution is available.
         */
        SignatureFallback: {
            contract?: components["schemas"]["DecodedContract"];
            /** Format: bytes */
            selector: string;
            candidates: string[];
        };
        /** SimulateTransactionRequest */
        SimulateTransactionRequest: {
            /** Format: address */
            from?: string;
            /** Format: address */
            to: string;
            /** Format: uint256 */
            value?: string;
            /** Format: bytes */
            data?: string;
        };
        /** SimulateTransactionResponse */
        SimulateTransactionResponse: {
            call: components["schemas"]["DecodedCall"];
        };
        /** Tx */
        Tx: {
            /** Format: uint64 */
            network_identity: number;
            /** Format: bytes */
            tx_hash?: string;
            /** Format: address */
            from?: string;
            /** Format: address */
            to?: string;
            /** Format: bytes */
            data?: string;
            /** Format: uint256 */
            value: string;
            decoded?: components["schemas"]["DecodedCall"];
            extra: components["schemas"]["TxExtra"];
        };
        /** TxExtra */
        TxExtra: {
            safe_wallet?: components["schemas"]["SafeWalletTxExtra"];
        };
        /** UniswapV2Pair */
        UniswapV2Pair: {
            pair_address: string;
            reserve_0?: string;
            reserve_1?: string;
        };
        /** UniswapV2QuoterConfig */
        UniswapV2QuoterConfig: {
            pair_address: string;
        };
        /** UniswapV3Pool */
        UniswapV3Pool: {
            pool_address: string;
            /** Format: uint32 */
            fee: number;
            reserve_0?: string;
            reserve_1?: string;
        };
        /** UniswapV3QuoterConfig */
        UniswapV3QuoterConfig: {
            pool_address: string;
        };
        /** @enum {string} */
        VendorFlag: "avara_asset_icons" | "zerion_asset_icons" | "smoldapp_asset_icons" | "smoldapp_network_icons" | "safewallet_network_icons" | "safewallet_asset_icons" | "safewallet_transactions_api" | "etherscan_asset_icons" | "etherscan_link_tx_hash" | "etherscan_link_address" | "etherscan_link_block" | "etherscan_link_contracts" | "blockscout_asset_icons" | "blockscout_link_tx_hash" | "blockscout_link_address" | "blockscout_link_block" | "blockscout_link_contracts";
        /** VendorFlagInfo */
        VendorFlagInfo: {
            flag: components["schemas"]["VendorFlag"];
            comment: string;
            unfinished: boolean;
        };
        /** VendorFlagInfoResponse */
        VendorFlagInfoResponse: {
            vendors: components["schemas"]["VendorFlagInfo"][];
        };
        /** VendorsResponse */
        VendorsResponse: {
            vendors: components["schemas"]["VendorFlag"][];
        };
        /** ViewWallet */
        ViewWallet: {
            /** Format: address */
            evm_address: string;
        };
        WalletType: components["schemas"]["WalletType_Safe"] | components["schemas"]["WalletType_EOA"] | components["schemas"]["WalletType_View"] | components["schemas"]["WalletType_Railgun"];
        WalletType_EOA: {
            /**
             * @example eoa
             * @enum {string}
             */
            type: "eoa";
        } & components["schemas"]["EOAWallet"];
        WalletType_Railgun: {
            /**
             * @example railgun
             * @enum {string}
             */
            type: "railgun";
        } & components["schemas"]["RailgunWallet"];
        WalletType_Safe: {
            /**
             * @example safe
             * @enum {string}
             */
            type: "safe";
        } & components["schemas"]["SafeWallet"];
        WalletType_View: {
            /**
             * @example view
             * @enum {string}
             */
            type: "view";
        } & components["schemas"]["ViewWallet"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
